import type { TextStyle } from "react-native";

export const typography: Record<string, TextStyle> = {
  heroDisplay: {
    fontFamily: "SF Pro Display",
    fontSize: 56,
    fontWeight: "600",
    lineHeight: 60,
    letterSpacing: -0.28,
  },
  displayLg: {
    fontFamily: "SF Pro Display",
    fontSize: 40,
    fontWeight: "600",
    lineHeight: 44,
    letterSpacing: 0,
  },
  displayMd: {
    fontFamily: "SF Pro Text",
    fontSize: 34,
    fontWeight: "600",
    lineHeight: 50,
    letterSpacing: -0.374,
  },
  lead: {
    fontFamily: "SF Pro Display",
    fontSize: 28,
    fontWeight: "400",
    lineHeight: 32,
    letterSpacing: 0.196,
  },
  leadAiry: {
    fontFamily: "SF Pro Text",
    fontSize: 24,
    fontWeight: "300",
    lineHeight: 36,
    letterSpacing: 0,
  },
  tagline: {
    fontFamily: "SF Pro Display",
    fontSize: 21,
    fontWeight: "600",
    lineHeight: 25,
    letterSpacing: 0.231,
  },
  bodyStrong: {
    fontFamily: "SF Pro Text",
    fontSize: 17,
    fontWeight: "600",
    lineHeight: 21,
    letterSpacing: -0.374,
  },
  body: {
    fontFamily: "SF Pro Text",
    fontSize: 17,
    fontWeight: "400",
    lineHeight: 25,
    letterSpacing: -0.374,
  },
  denseLink: {
    fontFamily: "SF Pro Text",
    fontSize: 17,
    fontWeight: "400",
    lineHeight: 41,
    letterSpacing: 0,
  },
  caption: {
    fontFamily: "SF Pro Text",
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    letterSpacing: -0.224,
  },
  captionStrong: {
    fontFamily: "SF Pro Text",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 18,
    letterSpacing: -0.224,
  },
  buttonLarge: {
    fontFamily: "SF Pro Text",
    fontSize: 18,
    fontWeight: "300",
    lineHeight: 18,
    letterSpacing: 0,
  },
  buttonUtility: {
    fontFamily: "SF Pro Text",
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 18,
    letterSpacing: -0.224,
  },
  finePrint: {
    fontFamily: "SF Pro Text",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 12,
    letterSpacing: -0.12,
  },
  microLegal: {
    fontFamily: "SF Pro Text",
    fontSize: 10,
    fontWeight: "400",
    lineHeight: 13,
    letterSpacing: -0.08,
  },
  navLink: {
    fontFamily: "SF Pro Text",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 12,
    letterSpacing: -0.12,
  },
};
