import type { AdminStore, AdminStoreSettings } from "@/redux/api/admin-api";
import type { Plan } from "@/redux/api/store-api";

export type TabHelpers = {
  storeId: string;
  store: AdminStore | null;
  plans: Plan[];
  settingsData?: AdminStoreSettings;
  statsData?: Record<string, unknown>;
  mediaData?: Record<string, unknown>;
  isLoading: boolean;
  dirty: boolean;
  markDirty: () => void;
  saving: boolean;
  handleSave: () => Promise<void>;
  localLimits: Record<string, unknown>;
  setLocalLimits: React.Dispatch<React.SetStateAction<Record<string, unknown>>>;
  localFeatures: Record<string, unknown>;
  setLocalFeatures: React.Dispatch<React.SetStateAction<Record<string, unknown>>>;
  localStorageMB: number | null;
  setLocalStorageMB: React.Dispatch<React.SetStateAction<number | null>>;
  localStorageUnlimited: boolean;
  setLocalStorageUnlimited: React.Dispatch<React.SetStateAction<boolean>>;
  localTrialEnabled: boolean | null;
  setLocalTrialEnabled: React.Dispatch<React.SetStateAction<boolean | null>>;
  localTrialEndsAt: string;
  setLocalTrialEndsAt: React.Dispatch<React.SetStateAction<string>>;
  localSubStatusOverride: string | null;
  setLocalSubStatusOverride: React.Dispatch<React.SetStateAction<string | null>>;
  localBillingStatusOverride: string | null;
  setLocalBillingStatusOverride: React.Dispatch<React.SetStateAction<string | null>>;
  localPlanId: string | null;
  setLocalPlanId: React.Dispatch<React.SetStateAction<string | null>>;
  localMaintenanceMode: boolean;
  setLocalMaintenanceMode: React.Dispatch<React.SetStateAction<boolean>>;
  localLoginDisabled: boolean;
  setLocalLoginDisabled: React.Dispatch<React.SetStateAction<boolean>>;
  changePlan: (planId: string) => Promise<unknown>;
  manageTrial: (action: string, days?: number, endsAt?: string) => Promise<unknown>;
  manageSub: (action: string) => Promise<unknown>;
  resetStore: (type: string) => Promise<unknown>;
  recalculate: () => Promise<unknown>;
  syncSub: () => Promise<unknown>;
  deleteCascade: () => Promise<unknown>;
  manageStaff: (action: string, teamMemberId?: string, role?: string) => Promise<unknown>;
  handleSuspend: () => void;
  handleActivate: () => void;
  refetchSettings: () => void;
};
