/**
 * Test data generators and tracking for safe automated QA
 */

export const QA_PREFIX = "QA-AUTO";

export function generateTestId(resource: string): string {
  const now = new Date();
  const timestamp = now.toISOString().replace(/[-:T.Z]/g, "").slice(0, 14);
  const rand = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `${QA_PREFIX}-${resource}-${timestamp}-${rand}`;
}

export function isAutoGeneratedTestRecord(nameOrSku: string): boolean {
  return typeof nameOrSku === "string" && nameOrSku.startsWith(QA_PREFIX);
}
