import type { ThemeDefinition } from "../types";

export const ELECTRONICS_THEME: ThemeDefinition = {
  id: "electronics",
  name: "Electronics & Tech",
  slug: "electronics",
  description: "A high-performance Bangladeshi tech & electronics e-commerce theme inspired by modern computer retail layouts with dark navy header, mega navigation, spec comparison, discount badges, and store locator.",
  category: "electronics",
  previewImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80",
  mobilePreviewImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80",
  version: "2.0.0",
  author: "BornoLand",
  tags: ["Electronics", "Computer", "Laptop", "Gaming", "Gadgets", "StarTech-style", "Tech"],

  tokens: {
    colors: {
      primary: "#081621", // Dark navy
      secondary: "#ef4444", // Tech red/crimson accent
      background: "#f2f4f8", // Crisp tech light gray
      surface: "#ffffff",
      text: "#0f172a", // Dark slate
      textMuted: "#64748b",
      border: "#e2e8f0",
      accent: "#e2136e", // Magenta/red promo accent
      accentHover: "#be123c",
      badgeBg: "#fee2e2",
      badgeText: "#ef4444",
      headerBg: "#081621", // Dark navy header
      headerText: "#ffffff",
      footerBg: "#081621", // Deep dark navy footer
      footerText: "#94a3b8",
    },
    typography: {
      fontFamily: "Inter, system-ui, sans-serif",
      headingFont: "Inter, system-ui, sans-serif",
      bodyFont: "Inter, system-ui, sans-serif",
      headingWeight: "700",
      baseFontSize: "14px",
    },
    layout: {
      containerWidth: "1320px",
      borderRadius: 8, // Crisp angular tech radius
      shadowSize: "sm",
      spacing: 20,
      gridGap: "16px",
    },
    cards: {
      productCardStyle: "electronics",
      categoryCardStyle: "electronics-tile",
      showBadges: true,
      showRatings: true,
      showAddToCart: true,
      showWishlist: true,
      showQuickView: true,
    },
  },

  header: {
    layout: "electronics",
    showAnnouncement: true,
    announcementText: "⚡ Mega Tech Deals 2026: Up to ৳15,000 Cashback on Selected Gaming Laptops & GPUs | All Bangladesh Express Delivery",
    announcementBg: "#e2136e",
    announcementTextColor: "#ffffff",
    showSearch: true,
    searchPlaceholder: "Search for Laptop, Desktop, GPU, Monitor, Accessories...",
    showWishlist: true,
    showCart: true,
    showAccount: true,
    showMegaMenu: true,
    showCategoryBar: true,
    sticky: true,
    logoHeight: 40,
    mobileMenuType: "drawer",
    quickLinks: [
      { label: "Offers", href: "/offers", icon: "Tag" },
      { label: "PC Builder", href: "/pc-builder", icon: "Cpu" },
      { label: "Compare", href: "/compare", icon: "Columns" },
      { label: "Store Locator", href: "/branches", icon: "MapPin" },
    ],
  },

  footer: {
    layout: "electronics",
    columns: 4,
    aboutText: "Leading tech retail & online shop in Bangladesh offering genuine laptops, desktop components, gaming gear, monitors, and gadgets with official brand warranty.",
    hotline: "16789 (9 AM - 8 PM)",
    email: "support@bornoland-tech.com",
    address: "6th Floor, Multiplan Center, Elephant Road, Dhaka-1205",
    showSocial: true,
    showNewsletter: true,
    showPaymentIcons: true,
    showAppLinks: true,
    showCopyright: true,
    copyrightText: `© ${new Date().getFullYear()} BornoLand Electronics Ltd. All rights reserved.`,
  },

  defaultSections: [
    {
      id: "electronics-hero",
      type: "slider-hero",
      label: "Hero Slider with Promo Grid",
      visible: true,
      props: {
        headline: "Next-Gen Gaming & AI Laptops",
        subheadline: "Powered by Latest Gen Processors & RTX Graphics. Official Warranty & 0% EMI Available.",
        buttonText: "Explore Laptops",
        buttonLink: "/category/laptops",
        secondaryButtonText: "Build Your PC",
        secondaryButtonLink: "/pc-builder",
        heroHeight: "md",
        imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1600&q=80",
        overlayColor: "rgba(8, 22, 33, 0.5)",
        textAlignment: "left",
      },
    },
    {
      id: "electronics-quick-links",
      type: "quick-service-links",
      label: "Quick Service Shortcuts",
      visible: true,
      props: {
        item1Title: "Laptop Finder",
        item1Subtitle: "Find your ideal laptop in 3 steps",
        item1Link: "/laptop-finder",
        item1Icon: "Laptop",
        item2Title: "Raise a Complaint",
        item2Subtitle: "Fast customer RMA & warranty support",
        item2Link: "/support",
        item2Icon: "Headphones",
        item3Title: "Online Service",
        item3Subtitle: "Expert remote PC diagnostic",
        item3Link: "/service",
        item3Icon: "Wrench",
        item4Title: "20+ Physical Stores",
        item4Subtitle: "Visit nearest store across BD",
        item4Link: "/branches",
        item4Icon: "Store",
      },
    },
    {
      id: "electronics-categories",
      type: "category-grid",
      label: "Featured Tech Categories",
      visible: true,
      props: {
        title: "Featured Categories",
        subtitle: "Get Your Desired Product from Featured Category!",
        gridColumns: "6",
        cardStyle: "electronics-tile",
        showProductCount: "true",
      },
    },
    {
      id: "electronics-store-banner",
      type: "store-locator-banner",
      label: "Physical Store Locator Banner",
      visible: true,
      props: {
        headline: "20+ Physical Stores Across Bangladesh",
        subheadline: "Experience products before you buy. Outlets in Dhaka, Chittagong, Sylhet, Rajshahi, Khulna, and Rangpur.",
        buttonText: "Find Nearest Store",
        buttonLink: "/branches",
        bgColor: "#0071dc",
        textColor: "#ffffff",
      },
    },
    {
      id: "electronics-featured-products",
      type: "featured-products",
      label: "Featured Tech Products",
      visible: true,
      props: {
        title: "Featured Products",
        subtitle: "Check & Get Your Desired Product!",
        gridColumns: "5",
        productCount: "10",
        showBadges: "true",
        showRatings: "true",
        showViewAll: "true",
        viewAllLink: "/shop",
      },
    },
    {
      id: "electronics-brands",
      type: "brand-showcase",
      label: "Top Tech Brands",
      visible: true,
      props: {
        title: "Popular Brands",
        subtitle: "Official authorized distributor products with authentic warranty",
      },
    },
    {
      id: "electronics-deals",
      type: "best-sellers",
      label: "Top Selling Components & Gadgets",
      visible: true,
      props: {
        title: "Best Selling Components & Accessories",
        subtitle: "Most popular choices amongst gamers & content creators",
        gridColumns: "5",
        productCount: "10",
        showBadges: "true",
        showRatings: "true",
      },
    },
    {
      id: "electronics-promo-banner",
      type: "discount-banner",
      label: "Flash Sale Banner",
      visible: true,
      props: {
        headline: "Upgrade Your Battlestation Today",
        subheadline: "Get up to 35% discount on gaming monitors, mechanical keyboards & headsets",
        discountText: "UP TO 35% OFF",
        buttonText: "View Deals",
        buttonLink: "/deals",
        bgColor: "#081621",
        textColor: "#ffffff",
      },
    },
    {
      id: "electronics-seo",
      type: "seo-content",
      label: "Leading Computer & Tech Retail Content",
      visible: true,
      props: {
        title: "Leading Computer, Laptop & Gaming PC Retail & Online Shop in Bangladesh",
        contentSnippet: "Technology has become an integral part of our daily lives, and for that, we need reliable computing devices. Whether you are building a custom gaming PC, buying an ultrabook laptop for office work, or upgrading your desktop with an RTX graphics card, BornoLand Electronics brings genuine products with official manufacturer warranty at the best prices in Bangladesh.",
        showFullContent: "false",
      },
    },
    {
      id: "electronics-trust-badges",
      type: "trust-badges",
      label: "Service & Trust Badges",
      visible: true,
      props: {
        title: "Why Choose BornoLand Tech?",
        subtitle: "100% Genuine Products • Official Warranty • Fast Nationwide Delivery",
      },
    },
    {
      id: "electronics-newsletter",
      type: "newsletter",
      label: "Tech Newsletter & Drop Alerts",
      visible: true,
      props: {
        headline: "Subscribe for Tech Deals & Price Drops",
        subheadline: "Get weekly updates on new hardware arrivals, flash discounts, and giveaway contests.",
        buttonText: "Subscribe",
        placeholderText: "Enter your email address...",
        bgColor: "#081621",
        textColor: "#ffffff",
      },
    },
  ],

  supportedSections: [
    "slider-hero", "hero-banner", "quick-service-links", "category-grid",
    "store-locator-banner", "featured-products", "brand-showcase", "best-sellers",
    "discount-banner", "seo-content", "trust-badges", "newsletter",
    "faq", "rich-text", "image-carousel"
  ],

  productCardVariant: "electronics",
  categoryCardVariant: "electronics-tile",
};
