import { z } from "zod";
import { SUBSCRIPTION_DURATIONS } from "../subscriptions/subscription.constants.js";

const planLimitsSchema = z.object({
  storage: z.number().min(0).optional().default(512),
  products: z.number().min(0).optional().default(10),
  categories: z.number().min(0).optional().default(5),
  collections: z.number().min(0).optional().default(5),
  brands: z.number().min(0).optional().default(3),
  productVariants: z.number().min(0).optional().default(0),
  productImages: z.number().min(0).optional().default(5),
  orders: z.number().min(0).optional().default(50),
  customers: z.number().min(0).optional().default(50),
  staff: z.number().min(0).optional().default(1),
  warehouses: z.number().min(0).optional().default(0),
  blogs: z.number().min(0).optional().default(0),
  pages: z.number().min(0).optional().default(5),
  mediaUploads: z.number().min(0).optional().default(100),
  apiKeys: z.number().min(0).optional().default(0),
  customDomains: z.number().min(0).optional().default(0),
  coupons: z.number().min(0).optional().default(0),
  shippingZones: z.number().min(0).optional().default(1),
  pickupLocations: z.number().min(0).optional().default(0),
  paymentMethods: z.number().min(0).optional().default(1),
  activeThemes: z.number().min(0).optional().default(1),
  builderPages: z.number().min(0).optional().default(3),
  menus: z.number().min(0).optional().default(1),
  navItems: z.number().min(0).optional().default(10),
  reviews: z.number().min(0).optional().default(0),
  testimonials: z.number().min(0).optional().default(0),
  announcements: z.number().min(0).optional().default(0),
  newsletterSubscribers: z.number().min(0).optional().default(0),
  campaigns: z.number().min(0).optional().default(0),
  emailTemplates: z.number().min(0).optional().default(0),
  automationRules: z.number().min(0).optional().default(0),
  integrations: z.number().min(0).optional().default(0),
  webhooks: z.number().min(0).optional().default(0),
  languages: z.number().min(0).optional().default(1),
  currencies: z.number().min(0).optional().default(1),
  taxRules: z.number().min(0).optional().default(0),
  inventoryLocations: z.number().min(0).optional().default(1),
  posDevices: z.number().min(0).optional().default(0),
  giftCards: z.number().min(0).optional().default(0),
  returnRequests: z.number().min(0).optional().default(0),
  wishlistItems: z.number().min(0).optional().default(0),
  analyticsReports: z.number().min(0).optional().default(0),
  exportRequests: z.number().min(0).optional().default(0),
  staffRoles: z.number().min(0).optional().default(1),
  cmsBlocks: z.number().min(0).optional().default(0),
  dynamicSections: z.number().min(0).optional().default(0),
  builderTemplates: z.number().min(0).optional().default(0),
  forms: z.number().min(0).optional().default(0),
  popups: z.number().min(0).optional().default(0),
  qrCodes: z.number().min(0).optional().default(0),
  redirectRules: z.number().min(0).optional().default(0),
  customCss: z.number().min(0).optional().default(0),
  customJs: z.number().min(0).optional().default(0),
  customFonts: z.number().min(0).optional().default(0),
});

const planFeatureSchema = z.object({
  productVariants: z.boolean().optional().default(false),
  inventory: z.boolean().optional().default(false),
  advancedInventory: z.boolean().optional().default(false),
  digitalProducts: z.boolean().optional().default(false),
  physicalProducts: z.boolean().optional().default(false),
  subscriptions: z.boolean().optional().default(false),
  bookings: z.boolean().optional().default(false),
  giftCards: z.boolean().optional().default(false),
  coupons: z.boolean().optional().default(false),
  reviews: z.boolean().optional().default(false),
  blog: z.boolean().optional().default(false),
  cms: z.boolean().optional().default(false),
  pageBuilder: z.boolean().optional().default(false),
  dragDropBuilder: z.boolean().optional().default(false),
  themeEditor: z.boolean().optional().default(false),
  advancedAnalytics: z.boolean().optional().default(false),
  seo: z.boolean().optional().default(false),
  aiContent: z.boolean().optional().default(false),
  customDomain: z.boolean().optional().default(false),
  subdomain: z.boolean().optional().default(true),
  whiteLabel: z.boolean().optional().default(false),
  apiAccess: z.boolean().optional().default(false),
  webhooks: z.boolean().optional().default(false),
  staffManagement: z.boolean().optional().default(false),
  marketplace: z.boolean().optional().default(false),
  pos: z.boolean().optional().default(false),
  wholesale: z.boolean().optional().default(false),
  dropshipping: z.boolean().optional().default(false),
  shipping: z.boolean().optional().default(false),
  localPickup: z.boolean().optional().default(false),
  abandonedCart: z.boolean().optional().default(false),
  emailMarketing: z.boolean().optional().default(false),
  smsMarketing: z.boolean().optional().default(false),
  pushNotification: z.boolean().optional().default(false),
  liveChat: z.boolean().optional().default(false),
  fileManager: z.boolean().optional().default(false),
  mediaLibrary: z.boolean().optional().default(true),
  bulkImport: z.boolean().optional().default(false),
  bulkExport: z.boolean().optional().default(false),
  csvImport: z.boolean().optional().default(false),
  csvExport: z.boolean().optional().default(false),
  googleLogin: z.boolean().optional().default(false),
  facebookLogin: z.boolean().optional().default(false),
  otpLogin: z.boolean().optional().default(false),
  multiCurrency: z.boolean().optional().default(false),
  multiLanguage: z.boolean().optional().default(false),
  taxEngine: z.boolean().optional().default(false),
  invoiceGenerator: z.boolean().optional().default(false),
  customCheckout: z.boolean().optional().default(false),
  checkoutFields: z.boolean().optional().default(false),
  advancedCheckout: z.boolean().optional().default(false),
  loyaltyPoints: z.boolean().optional().default(false),
  referralSystem: z.boolean().optional().default(false),
  affiliateSystem: z.boolean().optional().default(false),
  storeVerification: z.boolean().optional().default(false),
  backupRestore: z.boolean().optional().default(false),
  auditLogs: z.boolean().optional().default(false),
  developerMode: z.boolean().optional().default(false),
  maintenanceMode: z.boolean().optional().default(false),
  darkMode: z.boolean().optional().default(false),
  visitorAnalytics: z.boolean().optional().default(false),
  realtimeVisitors: z.boolean().optional().default(false),
  analyticsExport: z.boolean().optional().default(false),
});

const planPricingSchema = z.object({
  monthly: z.number().min(0).optional().default(0),
  quarterly: z.number().min(0).optional().default(0),
  halfYearly: z.number().min(0).optional().default(0),
  yearly: z.number().min(0).optional().default(0),
  lifetime: z.number().min(0).optional().default(0),
});

export const planSchema = z.object({
  name: z.string().min(2).max(80),
  slug: z.string().min(2).max(50).regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens"),
  description: z.string().max(1000).optional().default(""),
  priceBDT: z.number().min(0),
  priceYearly: z.number().min(0).optional().default(0),
  isCustomPrice: z.boolean().optional().default(false),
  trialDays: z.number().min(0).optional().default(0),
  features: z.array(z.string().min(1)).optional().default([]),
  limits: planLimitsSchema.optional().default({ storage: 512, products: 10, categories: 5, collections: 5, brands: 3, productVariants: 0, productImages: 5, orders: 50, customers: 50, staff: 1, warehouses: 0, blogs: 0, pages: 5, mediaUploads: 100, apiKeys: 0, customDomains: 0, coupons: 0, shippingZones: 1, pickupLocations: 0, paymentMethods: 1, activeThemes: 1, builderPages: 3, menus: 1, navItems: 10, reviews: 0, testimonials: 0, announcements: 0, newsletterSubscribers: 0, campaigns: 0, emailTemplates: 0, automationRules: 0, integrations: 0, webhooks: 0, languages: 1, currencies: 1, taxRules: 0, inventoryLocations: 1, posDevices: 0, giftCards: 0, returnRequests: 0, wishlistItems: 0, analyticsReports: 0, exportRequests: 0, staffRoles: 1, cmsBlocks: 0, dynamicSections: 0, builderTemplates: 0, forms: 0, popups: 0, qrCodes: 0, redirectRules: 0, customCss: 0, customJs: 0, customFonts: 0 }),
  featureToggles: planFeatureSchema.optional(),
  pricing: planPricingSchema.optional().default({
    monthly: 0, quarterly: 0, halfYearly: 0, yearly: 0, lifetime: 0,
  }),
  customDomain: z.boolean().optional().default(false),
  prioritySupport: z.boolean().optional().default(false),
  sortOrder: z.number().int().min(0).optional().default(0),
  visible: z.boolean().optional().default(true),
  isRecommended: z.boolean().optional().default(false),
  isActive: z.boolean().optional().default(true),
});

export const updatePlanSchema = planSchema.partial().extend({
  slug: z.string().min(2).max(50).regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens").optional(),
});

export type PlanInput = z.infer<typeof planSchema>;
export type UpdatePlanInput = z.infer<typeof updatePlanSchema>;

export const planDurationSchema = z.enum(SUBSCRIPTION_DURATIONS);
