import mongoose, { type InferSchemaType } from "mongoose";

const { Schema, model, models } = mongoose;

const planLimitSchema = new Schema({
  storage: { type: Number, default: 512 },
  products: { type: Number, default: 10 },
  categories: { type: Number, default: 5 },
  collections: { type: Number, default: 5 },
  brands: { type: Number, default: 3 },
  productVariants: { type: Number, default: 0 },
  productImages: { type: Number, default: 5 },
  orders: { type: Number, default: 50 },
  customers: { type: Number, default: 50 },
  staff: { type: Number, default: 1 },
  warehouses: { type: Number, default: 0 },
  blogs: { type: Number, default: 0 },
  pages: { type: Number, default: 5 },
  mediaUploads: { type: Number, default: 100 },
  apiKeys: { type: Number, default: 0 },
  customDomains: { type: Number, default: 0 },
  coupons: { type: Number, default: 0 },
  shippingZones: { type: Number, default: 1 },
  pickupLocations: { type: Number, default: 0 },
  paymentMethods: { type: Number, default: 1 },
  activeThemes: { type: Number, default: 1 },
  builderPages: { type: Number, default: 3 },
  menus: { type: Number, default: 1 },
  navItems: { type: Number, default: 10 },
  reviews: { type: Number, default: 0 },
  testimonials: { type: Number, default: 0 },
  announcements: { type: Number, default: 0 },
  newsletterSubscribers: { type: Number, default: 0 },
  campaigns: { type: Number, default: 0 },
  emailTemplates: { type: Number, default: 0 },
  automationRules: { type: Number, default: 0 },
  integrations: { type: Number, default: 0 },
  webhooks: { type: Number, default: 0 },
  languages: { type: Number, default: 1 },
  currencies: { type: Number, default: 1 },
  taxRules: { type: Number, default: 0 },
  inventoryLocations: { type: Number, default: 1 },
  posDevices: { type: Number, default: 0 },
  giftCards: { type: Number, default: 0 },
  returnRequests: { type: Number, default: 0 },
  wishlistItems: { type: Number, default: 0 },
  analyticsReports: { type: Number, default: 0 },
  exportRequests: { type: Number, default: 0 },
  staffRoles: { type: Number, default: 1 },
  cmsBlocks: { type: Number, default: 0 },
  dynamicSections: { type: Number, default: 0 },
  builderTemplates: { type: Number, default: 0 },
  forms: { type: Number, default: 0 },
  popups: { type: Number, default: 0 },
  qrCodes: { type: Number, default: 0 },
  redirectRules: { type: Number, default: 0 },
  customCss: { type: Number, default: 0 },
  customJs: { type: Number, default: 0 },
  customFonts: { type: Number, default: 0 },
}, { _id: false });

const planFeatureSchema = new Schema({
  productVariants: { type: Boolean, default: false },
  inventory: { type: Boolean, default: false },
  advancedInventory: { type: Boolean, default: false },
  inventoryHistory: { type: Boolean, default: false },
  priceHistory: { type: Boolean, default: false },
  costHistory: { type: Boolean, default: false },
  suppliers: { type: Boolean, default: false },
  purchaseOrders: { type: Boolean, default: false },
  batchFifo: { type: Boolean, default: false },
  warehousesEnabled: { type: Boolean, default: false },
  barcode: { type: Boolean, default: false },
  inventoryReports: { type: Boolean, default: false },
  lowStockAlerts: { type: Boolean, default: false },
  stockTransfer: { type: Boolean, default: false },
  inventoryAuditLog: { type: Boolean, default: false },
  digitalProducts: { type: Boolean, default: false },
  physicalProducts: { type: Boolean, default: false },
  subscriptions: { type: Boolean, default: false },
  bookings: { type: Boolean, default: false },
  giftCards: { type: Boolean, default: false },
  coupons: { type: Boolean, default: false },
  reviews: { type: Boolean, default: false },
  blog: { type: Boolean, default: false },
  cms: { type: Boolean, default: false },
  pageBuilder: { type: Boolean, default: false },
  dragDropBuilder: { type: Boolean, default: false },
  themeEditor: { type: Boolean, default: false },
  advancedAnalytics: { type: Boolean, default: false },
  seo: { type: Boolean, default: false },
  aiContent: { type: Boolean, default: false },
  customDomain: { type: Boolean, default: false },
  subdomain: { type: Boolean, default: true },
  whiteLabel: { type: Boolean, default: false },
  apiAccess: { type: Boolean, default: false },
  webhooks: { type: Boolean, default: false },
  staffManagement: { type: Boolean, default: false },
  marketplace: { type: Boolean, default: false },
  pos: { type: Boolean, default: false },
  wholesale: { type: Boolean, default: false },
  dropshipping: { type: Boolean, default: false },
  shipping: { type: Boolean, default: false },
  localPickup: { type: Boolean, default: false },
  abandonedCart: { type: Boolean, default: false },
  incompleteOrders: { type: Boolean, default: false },
  checkoutRecovery: { type: Boolean, default: false },
  recoveryAnalytics: { type: Boolean, default: false },
  recoveryLinks: { type: Boolean, default: false },
  emailMarketing: { type: Boolean, default: false },
  smsMarketing: { type: Boolean, default: false },
  pushNotification: { type: Boolean, default: false },
  liveChat: { type: Boolean, default: false },
  fileManager: { type: Boolean, default: false },
  mediaLibrary: { type: Boolean, default: true },
  bulkImport: { type: Boolean, default: false },
  bulkExport: { type: Boolean, default: false },
  csvImport: { type: Boolean, default: false },
  csvExport: { type: Boolean, default: false },
  googleLogin: { type: Boolean, default: false },
  facebookLogin: { type: Boolean, default: false },
  otpLogin: { type: Boolean, default: false },
  multiCurrency: { type: Boolean, default: false },
  multiLanguage: { type: Boolean, default: false },
  taxEngine: { type: Boolean, default: false },
  invoiceGenerator: { type: Boolean, default: false },
  customCheckout: { type: Boolean, default: false },
  checkoutFields: { type: Boolean, default: false },
  advancedCheckout: { type: Boolean, default: false },
  loyaltyPoints: { type: Boolean, default: false },
  referralSystem: { type: Boolean, default: false },
  affiliateSystem: { type: Boolean, default: false },
  storeVerification: { type: Boolean, default: false },
  backupRestore: { type: Boolean, default: false },
  auditLogs: { type: Boolean, default: false },
  developerMode: { type: Boolean, default: false },
  maintenanceMode: { type: Boolean, default: false },
  darkMode: { type: Boolean, default: false },
  visitorAnalytics: { type: Boolean, default: true },
  realtimeVisitors: { type: Boolean, default: true },
  analyticsExport: { type: Boolean, default: true },
  reports: { type: Boolean, default: false },
  courier: { type: Boolean, default: false },
  sslcommerzPayment: { type: Boolean, default: false },
  metaPixel: { type: Boolean, default: false },
  tiktokPixel: { type: Boolean, default: false },
  customTracking: { type: Boolean, default: false },
  googleAnalytics: { type: Boolean, default: false },
  conversionTracking: { type: Boolean, default: false },
  advancedTracking: { type: Boolean, default: false },
  // ── HRM / People Module ──────────────────────────────────────
  hrm: { type: Boolean, default: false },
  hrmEmployees: { type: Boolean, default: false },
  hrmAttendance: { type: Boolean, default: false },
  hrmPayroll: { type: Boolean, default: false },
  hrmLeave: { type: Boolean, default: false },
  hrmSelfService: { type: Boolean, default: false },
  // ── ERP / Finance ─────────────────────────────────────────────
  accounting: { type: Boolean, default: false },
  // ── CRM & Operations ──────────────────────────────────────────
  crm: { type: Boolean, default: false },
  operations: { type: Boolean, default: false },
  // ── ERP Suite ─────────────────────────────────────────────────
  erpCore: { type: Boolean, default: false },
  erpFinance: { type: Boolean, default: false },
  erpInventory: { type: Boolean, default: false },
  erpProcurement: { type: Boolean, default: false },
  erpManufacturing: { type: Boolean, default: false },
  erpProjects: { type: Boolean, default: false },
}, { _id: false });

const planCourierAccessSchema = new Schema(
  {
    enabled: { type: Boolean, default: false },
    allProviders: { type: Boolean, default: false },
    providers: { type: [String], default: [] },
  },
  { _id: false },
);
const planPricingSchema = new Schema({
  monthly: { type: Number, default: 0 },
  quarterly: { type: Number, default: 0 },
  halfYearly: { type: Number, default: 0 },
  yearly: { type: Number, default: 0 },
  lifetime: { type: Number, default: 0 },
}, { _id: false });

const planSchema = new Schema({
  name: { type: String, required: true, trim: true },
  slug: { type: String, required: true, unique: true, lowercase: true, trim: true },
  description: { type: String, default: "", trim: true },
  priceBDT: { type: Number, required: true, min: 0 },
  priceYearly: { type: Number, default: 0, min: 0 },
  isCustomPrice: { type: Boolean, default: false },
  trialDays: { type: Number, default: 0, min: 0 },
  features: { type: [String], default: [] },
  limits: { type: planLimitSchema, default: () => ({}) },
  featureToggles: { type: planFeatureSchema, default: () => ({}) },
  courierAccess: { type: planCourierAccessSchema, default: () => ({}) },
  pricing: { type: planPricingSchema, default: () => ({}) },
  customDomain: { type: Boolean, default: false },
  prioritySupport: { type: Boolean, default: false },
  sortOrder: { type: Number, default: 0 },
  visible: { type: Boolean, default: true },
  isRecommended: { type: Boolean, default: false },
  isPopular: { type: Boolean, default: false },
  isActive: { type: Boolean, default: true },
}, { timestamps: true });

export type PlanDocument = InferSchemaType<typeof planSchema>;
export const PlanModel = models.Plan ?? model("Plan", planSchema);
