import type { ThemeDefinition } from "../types";

export const GROCERY_THEME: ThemeDefinition = {
  id: "grocery",
  name: "Grocery & Organic",
  slug: "grocery",
  description: "A premium Bangladeshi organic and grocery e-commerce theme with warm natural tones, rich category highlights, combo offers, and fast checkout.",
  category: "grocery",
  previewImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
  mobilePreviewImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80",
  version: "2.0.0",
  author: "BornoLand",
  tags: ["Grocery", "Organic", "Food", "Supermarket", "Bangladeshi", "Fresh"],

  tokens: {
    colors: {
      primary: "#e05a00", // Warm vibrant orange
      secondary: "#055c3a", // Deep forest green
      background: "#fcfaf7", // Warm off-white
      surface: "#ffffff",
      text: "#1c2826", // Deep charcoal
      textMuted: "#6b7280",
      border: "#ede7df",
      accent: "#f97316",
      accentHover: "#c2410c",
      badgeBg: "#eef7ee",
      badgeText: "#055c3a",
      headerBg: "#ffffff",
      headerText: "#1c2826",
      footerBg: "#11261f", // Dark organic green
      footerText: "#e2e8f0",
    },
    typography: {
      fontFamily: "Inter, 'Hind Siliguri', sans-serif",
      headingFont: "Inter, 'Hind Siliguri', sans-serif",
      bodyFont: "Inter, 'Hind Siliguri', sans-serif",
      headingWeight: "700",
      baseFontSize: "15px",
    },
    layout: {
      containerWidth: "1280px",
      borderRadius: 14,
      shadowSize: "sm",
      spacing: 24,
      gridGap: "20px",
    },
    cards: {
      productCardStyle: "grocery",
      categoryCardStyle: "grocery-pill",
      showBadges: true,
      showRatings: true,
      showAddToCart: true,
      showWishlist: true,
      showQuickView: true,
    },
  },

  header: {
    layout: "grocery",
    showAnnouncement: true,
    announcementText: "🌿 100% খাঁটি ও নির্ভেজাল পণ্যের প্রতিশ্রুতি | সারাদেশে ক্যাশ অন ডেলিভারি সুবিধা",
    announcementBg: "#055c3a",
    announcementTextColor: "#ffffff",
    showSearch: true,
    searchPlaceholder: "খাঁটি মধু, ঘি, খেজুর কিংবা পছন্দের পণ্য খুঁজুন...",
    showWishlist: true,
    showCart: true,
    showAccount: true,
    showCategoryBar: true,
    sticky: true,
    logoHeight: 44,
    mobileMenuType: "drawer",
    quickLinks: [
      { label: "অফারসমূহ", href: "/offers", icon: "Tag" },
      { label: "কম্বো প্যাক", href: "/combo-deals", icon: "Package" },
      { label: "হট ডিল", href: "/hot-deals", icon: "Flame" },
      { label: "আমাদের আউটলেট", href: "/outlets", icon: "MapPin" },
    ],
  },

  footer: {
    layout: "grocery",
    columns: 4,
    aboutText: "আমরা নিশ্চিত করি শতভাগ খাঁটি, প্রাকৃতিক ও স্বাস্থ্যসম্মত খাদ্যপণ্য সরাসরি আপনার ঘরে পৌঁছে দিতে। প্রতিটি পণ্যের গুণগত মান আমাদের সর্বোচ্চ অগ্রাধিকার।",
    hotline: "09613-800800",
    email: "support@bornoland-grocery.com",
    address: "বাড়ি #24, রোড #12, বনানী, ঢাকা-1213",
    showSocial: true,
    showNewsletter: true,
    showPaymentIcons: true,
    showAppLinks: true,
    showCopyright: true,
    copyrightText: `© ${new Date().getFullYear()} BornoLand Grocery. All rights reserved.`,
  },

  defaultSections: [
    {
      id: "grocery-hero",
      type: "slider-hero",
      label: "Hero Promotional Slider",
      visible: true,
      props: {
        headline: "প্রকৃতির আসল স্বাদ ও পুষ্টি",
        subheadline: "শতভাগ খাঁটি সুন্দরবনের মধু, গাওয়া ঘি, প্রিমিয়াম খেজুর ও অর্গানিক খাদ্যপণ্য",
        buttonText: "অর্ডার করুন",
        buttonLink: "/shop",
        secondaryButtonText: "সকল ক্যাটাগরি",
        secondaryButtonLink: "/categories",
        heroHeight: "md",
        imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1600&q=80",
        overlayColor: "rgba(17, 38, 31, 0.4)",
        textAlignment: "left",
      },
    },
    {
      id: "grocery-categories",
      type: "category-grid",
      label: "Featured Categories",
      visible: true,
      props: {
        title: "জনপ্রিয় ক্যাটাগরি",
        subtitle: "আপনার নিত্যদিনের প্রয়োজনীয় স্বাস্থ্যসম্মত খাদ্যপণ্য বেছে নিন",
        gridColumns: "6",
        cardStyle: "grocery-pill",
        showProductCount: "true",
      },
    },
    {
      id: "grocery-top-selling",
      type: "best-sellers",
      label: "Top Selling Products",
      visible: true,
      props: {
        title: "সর্বাধিক বিক্রিত পণ্য",
        subtitle: "গ্রাহকদের সবচেয়ে পছন্দের ও নির্ভরযোগ্য পণ্যসমূহ",
        gridColumns: "4",
        productCount: "8",
        showBadges: "true",
        showRatings: "true",
        showViewAll: "true",
        viewAllLink: "/shop",
      },
    },
    {
      id: "grocery-brands",
      type: "brand-showcase",
      label: "Our Brands & Farms",
      visible: true,
      props: {
        title: "আমাদের বিশ্বস্ত ব্র্যান্ডসমূহ",
        subtitle: "সরাসরি নিজস্ব ফার্ম এবং চুক্তিবদ্ধ কৃষকদের থেকে সংগৃহীত",
      },
    },
    {
      id: "grocery-natural",
      type: "featured-products",
      label: "All Natural & Pure Honey",
      visible: true,
      props: {
        title: "খাঁটি মধু ও প্রাকৃতিক খাবার",
        subtitle: "সুন্দরবনের প্রাকৃতিক চাকের মধু, কালোজিরা ফুলের মধু ও সরিষা মধু",
        gridColumns: "4",
        productCount: "4",
        showBadges: "true",
        showRatings: "true",
        showViewAll: "true",
        viewAllLink: "/category/honey",
      },
    },
    {
      id: "grocery-combo-deals",
      type: "combo-deals",
      label: "Exclusive Combo Deals",
      visible: true,
      props: {
        title: "ধামাকা কম্বো অফার",
        subtitle: "একসাথে কিনুন আর সাশ্রয় করুন আকর্ষণীয় মূল্যছাড়",
        badgeText: "অফারে সাশ্রয় করুন",
        gridColumns: "3",
        productCount: "3",
      },
    },
    {
      id: "grocery-promo-banner",
      type: "discount-banner",
      label: "Wide Promo Banner",
      visible: true,
      props: {
        headline: "এক কাপ খাঁটি দুধের মিষ্টি স্বাদ",
        subheadline: "গাওয়া ঘি ও প্রাকৃতিক খাদ্যপণ্যে 20% পর্যন্ত বিশেষ ছাড়",
        discountText: "UP TO 20% OFF",
        buttonText: "অফার লুফে নিন",
        buttonLink: "/offers",
        bgColor: "#055c3a",
        textColor: "#ffffff",
        bgImage: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=1600&q=80",
      },
    },
    {
      id: "grocery-cooking",
      type: "product-grid",
      label: "Cooking Essentials",
      visible: true,
      props: {
        title: "রান্নার প্রয়োজনীয় পণ্য",
        subtitle: "কাঠবাদাম তেল, ঘানি ভাঙা খাঁটি সরিষার তেল ও মসলা",
        gridColumns: "4",
        productCount: "8",
      },
    },
    {
      id: "grocery-testimonials",
      type: "testimonials",
      label: "Customer Reviews",
      visible: true,
      props: {
        title: "গ্রাহকদের অভিমত",
        subtitle: "হাজারো সন্তুষ্ট পরিবারের বিশ্বস্ততার প্রতীক",
        layout: "grid",
        cardStyle: "elevated",
        avatarStyle: "circle",
        testimonialsCount: "3",
      },
    },
    {
      id: "grocery-trust-badges",
      type: "trust-badges",
      label: "Quality & Trust Badges",
      visible: true,
      props: {
        title: "আমাদের বিশেষত্ব",
        subtitle: "কেন BornoLand Grocery থেকে পণ্য কিনবেন?",
      },
    },
    {
      id: "grocery-newsletter",
      type: "newsletter",
      label: "Newsletter & Offer Alerts",
      visible: true,
      props: {
        headline: "বিশেষ অফার ও নতুন পণ্যের আপডেট পান",
        subheadline: "আপনার ইমেইল দিয়ে সাবস্ক্রাইব করুন এবং প্রথম অর্ডারে 10% ছাড় উপভোগ করুন।",
        buttonText: "সাবস্ক্রাইব",
        placeholderText: "আপনার ইমেইল লিখুন...",
        bgColor: "#f3ede3",
        textColor: "#1c2826",
      },
    },
  ],

  supportedSections: [
    "slider-hero", "hero-banner", "category-grid", "best-sellers",
    "featured-products", "brand-showcase", "combo-deals", "discount-banner",
    "product-grid", "testimonials", "trust-badges", "newsletter",
    "faq", "rich-text", "seo-content", "store-locator-banner", "image-carousel"
  ],

  productCardVariant: "grocery",
  categoryCardVariant: "grocery-pill",
};
