/**
 * Default plan ↔ feature matrix.
 * Inserted with $setOnInsert only — Super Admin customizations are preserved.
 *
 * limit: 0 = unlimited for limit-type features
 */
export type PlanFeatureDefault = {
  enabled?: boolean;
  limit?: number;
  tierKey?: string;
};

export const DEFAULT_PLAN_FEATURE_MATRIX: Record<string, Record<string, PlanFeatureDefault>> = {
  free: {
    products: { enabled: true, limit: 50 },
    orders: { enabled: true, limit: 100 },
    customers: { enabled: true, limit: 0 },
    categories: { enabled: true, limit: 10 },
    inventory: { enabled: true },
    inventory_history: { enabled: false },
    price_history: { enabled: false },
    cost_history: { enabled: false },
    suppliers: { enabled: false },
    purchase_orders: { enabled: false },
    batch_fifo: { enabled: false },
    warehouses: { enabled: false },
    barcode: { enabled: false },
    inventory_reports: { enabled: false },
    low_stock_alerts: { enabled: false },
    stock_transfer: { enabled: false },
    inventory_audit_log: { enabled: false },
    product_variants: { enabled: false, limit: 0 },
    variant_bulk_tools: { enabled: false },
    shipping: { enabled: false },
    payment_gateway: { enabled: false },
    sslcommerz_payment: { enabled: false },
    courier: { enabled: false },
    pos: { enabled: false },
    coupons: { enabled: false },
    reviews: { enabled: false },
    discounts: { enabled: false },
    email_marketing: { enabled: false },
    abandoned_cart: { enabled: false },
    incomplete_orders: { enabled: false },
    checkout_recovery: { enabled: false },
    recovery_analytics: { enabled: false },
    marketing: { enabled: false },
    cms: { enabled: true },
    blog: { enabled: false },
    media: { enabled: true, limit: 0 },
    page_builder: { enabled: true, limit: 3 },
    builder: { enabled: true },
    theme_builder: { enabled: true },
    custom_domain: { enabled: false },
    seo: { enabled: false, tierKey: "disabled" },
    analytics: { enabled: false, tierKey: "disabled" },
    reports: { enabled: false, tierKey: "disabled" },
    api_access: { enabled: false, tierKey: "disabled" },
    apps: { enabled: false },
    staff: { enabled: true, limit: 1 },
    storage: { enabled: true, limit: 0.5 },
    bandwidth: { enabled: true, limit: 2 },
    export: { enabled: false },
    import: { enabled: false },
    custom_code: { enabled: false },
    meta_pixel: { enabled: false },
    tiktok_pixel: { enabled: false },
    custom_tracking: { enabled: false },
    google_analytics: { enabled: false },
    conversion_tracking: { enabled: false },
    advanced_tracking: { enabled: false },
    ai_features: { enabled: false, tierKey: "none" },
    multi_language: { enabled: false },
    domains: { enabled: false, limit: 0 },
    templates: { enabled: true, limit: 1 },
    erp_core: { enabled: false },
    erp_finance: { enabled: false },
    erp_inventory: { enabled: false },
    erp_procurement: { enabled: false },
    erp_manufacturing: { enabled: false },
    erp_projects: { enabled: false },
  },
  starter: {
    products: { enabled: true, limit: 500 },
    orders: { enabled: true, limit: 1000 },
    customers: { enabled: true, limit: 0 },
    categories: { enabled: true, limit: 50 },
    inventory: { enabled: true },
    inventory_history: { enabled: true },
    price_history: { enabled: false },
    cost_history: { enabled: false },
    suppliers: { enabled: false },
    purchase_orders: { enabled: false },
    batch_fifo: { enabled: false },
    warehouses: { enabled: false },
    barcode: { enabled: true },
    inventory_reports: { enabled: false },
    low_stock_alerts: { enabled: true },
    stock_transfer: { enabled: false },
    inventory_audit_log: { enabled: false },
    product_variants: { enabled: true, limit: 50 },
    variant_bulk_tools: { enabled: false },
    shipping: { enabled: true },
    payment_gateway: { enabled: true },
    sslcommerz_payment: { enabled: true },
    courier: { enabled: false },
    pos: { enabled: false },
    coupons: { enabled: true },
    reviews: { enabled: true },
    discounts: { enabled: true },
    email_marketing: { enabled: false },
    abandoned_cart: { enabled: true },
    incomplete_orders: { enabled: true },
    checkout_recovery: { enabled: true },
    recovery_analytics: { enabled: false },
    marketing: { enabled: false },
    cms: { enabled: true },
    blog: { enabled: true },
    media: { enabled: true, limit: 0 },
    page_builder: { enabled: true, limit: 10 },
    builder: { enabled: true },
    theme_builder: { enabled: true },
    custom_domain: { enabled: false },
    seo: { enabled: true, tierKey: "basic" },
    analytics: { enabled: true, tierKey: "basic" },
    reports: { enabled: false, tierKey: "disabled" },
    api_access: { enabled: false, tierKey: "disabled" },
    apps: { enabled: false },
    staff: { enabled: true, limit: 3 },
    storage: { enabled: true, limit: 5 },
    bandwidth: { enabled: true, limit: 20 },
    export: { enabled: true },
    import: { enabled: true },
    custom_code: { enabled: false },
    meta_pixel: { enabled: true },
    tiktok_pixel: { enabled: true },
    custom_tracking: { enabled: false },
    google_analytics: { enabled: true },
    conversion_tracking: { enabled: false },
    advanced_tracking: { enabled: false },
    ai_features: { enabled: false, tierKey: "none" },
    multi_language: { enabled: false },
    domains: { enabled: false, limit: 0 },
    templates: { enabled: true, limit: 3 },
    erp_core: { enabled: false },
    erp_finance: { enabled: false },
    erp_inventory: { enabled: false },
    erp_procurement: { enabled: false },
    erp_manufacturing: { enabled: false },
    erp_projects: { enabled: false },
  },
  business: {
    products: { enabled: true, limit: 0 },
    orders: { enabled: true, limit: 0 },
    customers: { enabled: true, limit: 0 },
    categories: { enabled: true, limit: 200 },
    inventory: { enabled: true },
    inventory_history: { enabled: true },
    price_history: { enabled: true },
    cost_history: { enabled: true },
    suppliers: { enabled: true },
    purchase_orders: { enabled: true },
    batch_fifo: { enabled: false },
    warehouses: { enabled: true },
    barcode: { enabled: true },
    inventory_reports: { enabled: true },
    low_stock_alerts: { enabled: true },
    stock_transfer: { enabled: true },
    inventory_audit_log: { enabled: false },
    product_variants: { enabled: true, limit: 0 },
    variant_bulk_tools: { enabled: false },
    shipping: { enabled: true },
    payment_gateway: { enabled: true },
    sslcommerz_payment: { enabled: true },
    courier: { enabled: true },
    pos: { enabled: true },
    coupons: { enabled: true },
    reviews: { enabled: true },
    discounts: { enabled: true },
    email_marketing: { enabled: true },
    abandoned_cart: { enabled: true },
    incomplete_orders: { enabled: true },
    checkout_recovery: { enabled: true },
    recovery_analytics: { enabled: true },
    marketing: { enabled: true },
    cms: { enabled: true },
    blog: { enabled: true },
    media: { enabled: true, limit: 0 },
    page_builder: { enabled: true, limit: 50 },
    builder: { enabled: true },
    theme_builder: { enabled: true },
    custom_domain: { enabled: true },
    seo: { enabled: true, tierKey: "advanced" },
    analytics: { enabled: true, tierKey: "advanced" },
    reports: { enabled: true, tierKey: "basic" },
    api_access: { enabled: true, tierKey: "read_write" },
    apps: { enabled: true },
    staff: { enabled: true, limit: 10 },
    storage: { enabled: true, limit: 20 },
    bandwidth: { enabled: true, limit: 100 },
    export: { enabled: true },
    import: { enabled: true },
    custom_code: { enabled: false },
    meta_pixel: { enabled: true },
    tiktok_pixel: { enabled: true },
    custom_tracking: { enabled: true },
    google_analytics: { enabled: true },
    conversion_tracking: { enabled: true },
    advanced_tracking: { enabled: false },
    ai_features: { enabled: true, tierKey: "basic" },
    multi_language: { enabled: true },
    domains: { enabled: true, limit: 1 },
    templates: { enabled: true, limit: 10 },
    erp_core: { enabled: true },
    erp_finance: { enabled: true },
    erp_inventory: { enabled: true },
    erp_procurement: { enabled: false },
    erp_manufacturing: { enabled: false },
    erp_projects: { enabled: false },
  },
  enterprise: {
    products: { enabled: true, limit: 0 },
    orders: { enabled: true, limit: 0 },
    customers: { enabled: true, limit: 0 },
    categories: { enabled: true, limit: 0 },
    inventory: { enabled: true },
    inventory_history: { enabled: true },
    price_history: { enabled: true },
    cost_history: { enabled: true },
    suppliers: { enabled: true },
    purchase_orders: { enabled: true },
    batch_fifo: { enabled: true },
    warehouses: { enabled: true },
    barcode: { enabled: true },
    inventory_reports: { enabled: true },
    low_stock_alerts: { enabled: true },
    stock_transfer: { enabled: true },
    inventory_audit_log: { enabled: true },
    product_variants: { enabled: true, limit: 0 },
    variant_bulk_tools: { enabled: true },
    shipping: { enabled: true },
    payment_gateway: { enabled: true },
    sslcommerz_payment: { enabled: true },
    courier: { enabled: true },
    pos: { enabled: true },
    coupons: { enabled: true },
    reviews: { enabled: true },
    discounts: { enabled: true },
    email_marketing: { enabled: true },
    abandoned_cart: { enabled: true },
    incomplete_orders: { enabled: true },
    checkout_recovery: { enabled: true },
    recovery_analytics: { enabled: true },
    marketing: { enabled: true },
    cms: { enabled: true },
    blog: { enabled: true },
    media: { enabled: true, limit: 0 },
    page_builder: { enabled: true, limit: 0 },
    builder: { enabled: true },
    theme_builder: { enabled: true },
    custom_domain: { enabled: true },
    seo: { enabled: true, tierKey: "professional" },
    analytics: { enabled: true, tierKey: "enterprise" },
    reports: { enabled: true, tierKey: "enterprise" },
    api_access: { enabled: true, tierKey: "unlimited" },
    apps: { enabled: true },
    staff: { enabled: true, limit: 0 },
    storage: { enabled: true, limit: 100 },
    bandwidth: { enabled: true, limit: 0 },
    export: { enabled: true },
    import: { enabled: true },
    custom_code: { enabled: true },
    meta_pixel: { enabled: true },
    tiktok_pixel: { enabled: true },
    custom_tracking: { enabled: true },
    google_analytics: { enabled: true },
    conversion_tracking: { enabled: true },
    advanced_tracking: { enabled: true },
    ai_features: { enabled: true, tierKey: "enterprise" },
    multi_language: { enabled: true },
    domains: { enabled: true, limit: 0 },
    templates: { enabled: true, limit: 0 },
    erp_core: { enabled: true },
    erp_finance: { enabled: true },
    erp_inventory: { enabled: true },
    erp_procurement: { enabled: true },
    erp_manufacturing: { enabled: true },
    erp_projects: { enabled: true },
  },
};
