/**
 * Canonical default subscription plans.
 * Applied with $setOnInsert only — existing plans are never overwritten.
 */
export const DEFAULT_PLANS = [
  {
    name: "Free",
    slug: "free",
    description: "Get started with a basic storefront.",
    priceBDT: 0,
    priceYearly: 0,
    trialDays: 3,
    features: ["Basic storefront", "50 products", "500 MB storage", "Community support"],
    limits: {
      stores: 1,
      products: 50,
      orders: 100,
      categories: 10,
      staff: 1,
      storageGB: 0.5,
      bandwidthGB: 2,
      domains: 0,
      themes: 1,
      builderPages: 3,
      apiAccess: false,
      analytics: false,
      coupons: false,
      reviews: false,
      marketing: false,
      customCode: false,
    },
    pricing: { monthly: 0, quarterly: 0, halfYearly: 0, yearly: 0, lifetime: 0 },
    sortOrder: 1,
    isRecommended: false,
    isActive: true,
    visible: true,
  },
  {
    name: "Starter",
    slug: "starter",
    description: "For small businesses getting online.",
    priceBDT: 499,
    priceYearly: 4990,
    trialDays: 0,
    features: ["500 products", "5 GB storage", "Manual payments", "Email support"],
    limits: {
      stores: 1,
      products: 500,
      orders: 1000,
      categories: 50,
      staff: 3,
      storageGB: 5,
      bandwidthGB: 20,
      domains: 0,
      themes: 3,
      builderPages: 10,
      apiAccess: false,
      analytics: true,
      coupons: true,
      reviews: true,
      marketing: false,
      customCode: false,
    },
    pricing: { monthly: 499, quarterly: 1420, halfYearly: 2690, yearly: 4990, lifetime: 0 },
    sortOrder: 2,
    isRecommended: true,
    isActive: true,
    visible: true,
  },
  {
    name: "Business",
    slug: "business",
    description: "For growing brands with advanced needs.",
    priceBDT: 999,
    priceYearly: 9990,
    trialDays: 0,
    features: ["Unlimited products", "20 GB storage", "Custom domain", "Priority support"],
    limits: {
      stores: 1,
      products: 0,
      orders: 0,
      categories: 200,
      staff: 10,
      storageGB: 20,
      bandwidthGB: 100,
      domains: 1,
      themes: 10,
      builderPages: 50,
      apiAccess: true,
      analytics: true,
      coupons: true,
      reviews: true,
      marketing: true,
      customCode: false,
    },
    pricing: { monthly: 999, quarterly: 2840, halfYearly: 5390, yearly: 9990, lifetime: 0 },
    customDomain: true,
    prioritySupport: true,
    sortOrder: 3,
    isRecommended: false,
    isActive: true,
    visible: true,
  },
  {
    name: "Enterprise",
    slug: "enterprise",
    description: "Custom pricing for large organizations.",
    priceBDT: 0,
    priceYearly: 0,
    isCustomPrice: true,
    trialDays: 0,
    features: ["Unlimited products", "100 GB storage", "Dedicated support", "SLA"],
    limits: {
      stores: 999,
      products: 0,
      orders: 0,
      categories: 0,
      staff: 0,
      storageGB: 100,
      bandwidthGB: 0,
      domains: 0,
      themes: 0,
      builderPages: 0,
      apiAccess: true,
      analytics: true,
      coupons: true,
      reviews: true,
      marketing: true,
      customCode: true,
    },
    pricing: { monthly: 0, quarterly: 0, halfYearly: 0, yearly: 0, lifetime: 0 },
    customDomain: true,
    prioritySupport: true,
    sortOrder: 4,
    isRecommended: false,
    isActive: true,
    visible: true,
  },
] as const;
