import mongoose from "mongoose";
import dotenvFlow from "dotenv-flow";
import path from "path";
import { fileURLToPath } from "url";
import { connectDatabase } from "../common/database/connection.js";
import { StoreModel } from "../models/store.model.js";
import { CategoryModel } from "../models/category.model.js";
import { BrandModel } from "../models/brand.model.js";
import { ProductModel } from "../models/product.model.js";

// Ensure env is loaded
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenvFlow.config({ path: path.resolve(__dirname, "../../") });

export async function seedNayeemStoreData() {
  await connectDatabase();
  console.log("🌱 [Seed] Database connected.");

  const store = await StoreModel.findOne({ slug: "nayeem" });
  if (!store) {
    console.error("❌ [Seed] Store with slug 'nayeem' not found in database.");
    return { ok: false, message: "Store 'nayeem' not found" };
  }

  const storeId = store._id;
  console.log(`✅ [Seed] Found store "${store.name}" (${storeId})`);

  // ── 1. Seed 10 Top-Level Categories ───────────────────────────────────────
  const categoryDefs = [
    {
      name: "Honey",
      nameEn: "Honey",
      nameBn: "মধু ও সুইটনার",
      slug: "honey",
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      description: "100% Pure, raw, natural and organic honey from Sundarbans and mustard blossoms.",
      descriptionEn: "100% Pure, raw, natural and organic honey from Sundarbans and mustard blossoms.",
      descriptionBn: "সুন্দরবন ও সরিষা ফুলের ১০০% প্রাকৃতিক, খাঁটি ও ভেজালমুক্ত মধু।",
      sortOrder: 1,
    },
    {
      name: "Oil & Ghee",
      nameEn: "Oil & Ghee",
      nameBn: "তেল ও ঘি",
      slug: "oil-ghee",
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
      description: "Cold-pressed wood-pressed mustard oil, extra virgin olive oil, and pure cow ghee.",
      descriptionEn: "Cold-pressed wood-pressed mustard oil, extra virgin olive oil, and pure cow ghee.",
      descriptionBn: "কাঠের ঘানিতে ভাঙা খাঁটি সরিষার তেল, এক্সট্রা ভার্জিন অলিভ অয়েল ও প্রিমিয়াম গাওয়া ঘি।",
      sortOrder: 2,
    },
    {
      name: "Dates",
      nameEn: "Dates",
      nameBn: "প্রিমিয়াম খেজুর",
      slug: "dates",
      imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80",
      description: "Premium imported Madinah Ajwa, Jumbo Medjool, Safawi, and Sukkari dates.",
      descriptionEn: "Premium imported Madinah Ajwa, Jumbo Medjool, Safawi, and Sukkari dates.",
      descriptionBn: "সরাসরি মদিনা থেকে আমদানিকৃত প্রিমিয়াম আজওয়া, মরিয়ম, মেদজুল ও সুক্কারি খেজুর।",
      sortOrder: 3,
    },
    {
      name: "Spices",
      nameEn: "Spices",
      nameBn: "মসলাপাতি",
      slug: "spices",
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
      description: "Stone-ground authentic turmeric, red chili, cumin, coriander, and royal masala.",
      descriptionEn: "Stone-ground authentic turmeric, red chili, cumin, coriander, and royal masala.",
      descriptionBn: "ঢেঁকি ও পাথরে ভাঙা খাঁটি হলুদ, মরিচ, ধনিয়া, জিরা ও শাহী গরম মসলা।",
      sortOrder: 4,
    },
    {
      name: "Nuts & Seeds",
      nameEn: "Nuts & Seeds",
      nameBn: "বাদাম ও বীজ",
      slug: "nuts-seeds",
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      description: "Premium roasted cashew nuts, California almonds, walnuts, chia and pumpkin seeds.",
      descriptionEn: "Premium roasted cashew nuts, California almonds, walnuts, chia and pumpkin seeds.",
      descriptionBn: "প্রিমিয়াম রোস্টেড কাজুবাদাম, কাঠবাদাম, আখরোট, চিয়া সিড ও মিষ্টি কুমড়ার বীজ।",
      sortOrder: 5,
    },
    {
      name: "Organic Food",
      nameEn: "Organic Food",
      nameBn: "অর্গানিক ফুড",
      slug: "organic-food",
      imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop&q=80",
      description: "Certified organic superfoods, apple cider vinegar, and pink Himalayan salt.",
      descriptionEn: "Certified organic superfoods, apple cider vinegar, and pink Himalayan salt.",
      descriptionBn: "সার্টিফাইড অর্গানিক সুপারফুড, অ্যাপল সাইডার ভিনেগার ও পিঙ্ক হিমালয়ান সল্ট।",
      sortOrder: 6,
    },
    {
      name: "Rice & Grains",
      nameEn: "Rice & Grains",
      nameBn: "চাল ও খাদ্যশস্য",
      slug: "rice-grains",
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      description: "Aromatic Kalijira rice, royal Basmati, organic red rice, and whole grains.",
      descriptionEn: "Aromatic Kalijira rice, royal Basmati, organic red rice, and whole grains.",
      descriptionBn: "সুগন্ধি দিনাজপুরের কাটারিভোগ ও কালিজিরা চাল, রাজকীয় বাসমতী ও লাল চাল।",
      sortOrder: 7,
    },
    {
      name: "Beverages",
      nameEn: "Beverages",
      nameBn: "চা ও কফি",
      slug: "beverages",
      imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
      description: "Organic Sylhet green tea, artisan masala chai, roasted coffee beans.",
      descriptionEn: "Organic Sylhet green tea, artisan masala chai, roasted coffee beans.",
      descriptionBn: "শ্রীমঙ্গলের প্রিমিয়াম গ্রিন টি, মসলা চা ও খাঁটি রোস্টেড অ্যারাবিকা কফি বিন।",
      sortOrder: 8,
    },
    {
      name: "Snacks",
      nameEn: "Snacks",
      nameBn: "মুখরোচক স্ন্যাক্স",
      slug: "snacks",
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      description: "Spicy handmade chanachur, roasted peanuts, dry fruit mixes, and Nakshi pitha.",
      descriptionEn: "Spicy handmade chanachur, roasted peanuts, dry fruit mixes, and Nakshi pitha.",
      descriptionBn: "ঘরোয়া মসলাদার চানাচুর, কাজু বাদাম ফ্রাই, ড্রাই ফ্রুট মিক্স ও ঐতিহ্যবাহী নকশি পিঠা।",
      sortOrder: 9,
    },
    {
      name: "Cooking Essentials",
      nameEn: "Cooking Essentials",
      nameBn: "রান্নার অনুষঙ্গ",
      slug: "cooking-essentials",
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      description: "Unrefined brown sugar, whole wheat atta, pure cane vinegar, and staples.",
      descriptionEn: "Unrefined brown sugar, whole wheat atta, pure cane vinegar, and staples.",
      descriptionBn: "অশোধিত লাল চিনি, খাঁটি গুড়, চাক্কি আটা ও প্রাকৃতিক ভিনেগার।",
      sortOrder: 10,
    },
  ];

  const categoryMap = new Map<string, mongoose.Types.ObjectId>();

  for (const def of categoryDefs) {
    const cat = await CategoryModel.findOneAndUpdate(
      { storeId, slug: def.slug },
      {
        $set: {
          storeId,
          name: def.name,
          nameEn: def.nameEn,
          nameBn: def.nameBn,
          slug: def.slug,
          imageUrl: def.imageUrl,
          description: def.description,
          descriptionEn: def.descriptionEn,
          descriptionBn: def.descriptionBn,
          parentId: null,
          active: true,
          featured: true,
          sortOrder: def.sortOrder,
        },
      },
      { upsert: true, new: true }
    );
    categoryMap.set(def.slug, cat._id as mongoose.Types.ObjectId);
  }
  console.log(`✅ [Seed] Upserted 10 Top-Level Categories.`);

  // ── 2. Seed 35 Subcategories ──────────────────────────────────────────────
  const subcategoryDefs: Array<{
    parentSlug: string;
    name: string;
    slug: string;
    imageUrl: string;
    description: string;
  }> = [
    // Honey
    { parentSlug: "honey", name: "Raw Honey", slug: "raw-honey", imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&auto=format&fit=crop&q=80", description: "Unpasteurized raw honey directly from beehives" },
    { parentSlug: "honey", name: "Black Seed Honey", slug: "black-seed-honey", imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=500&auto=format&fit=crop&q=80", description: "Medicinal honey infused with organic black seed extract" },
    { parentSlug: "honey", name: "Sundarban Honey", slug: "sundarban-honey", imageUrl: "https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=500&auto=format&fit=crop&q=80", description: "Wild forest honey collected by traditional Mawals" },
    { parentSlug: "honey", name: "Organic Honey", slug: "organic-honey", imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80", description: "Certified pure natural flower honey" },

    // Oil & Ghee
    { parentSlug: "oil-ghee", name: "Mustard Oil", slug: "mustard-oil", imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80", description: "Wood-pressed pungent cold-extracted mustard oil" },
    { parentSlug: "oil-ghee", name: "Olive Oil", slug: "olive-oil", imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=500&auto=format&fit=crop&q=80", description: "Extra virgin first cold-pressed olive oil" },
    { parentSlug: "oil-ghee", name: "Coconut Oil", slug: "coconut-oil", imageUrl: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=80", description: "Raw extra virgin coconut oil for cooking and wellness" },
    { parentSlug: "oil-ghee", name: "Pure Ghee", slug: "pure-ghee", imageUrl: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=500&auto=format&fit=crop&q=80", description: "Traditional artisanal aroma-rich cow ghee" },

    // Dates
    { parentSlug: "dates", name: "Ajwa Dates", slug: "ajwa-dates", imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500&auto=format&fit=crop&q=80", description: "Authentic holy Madinah black Ajwa dates" },
    { parentSlug: "dates", name: "Medjool Dates", slug: "medjool-dates", imageUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=500&auto=format&fit=crop&q=80", description: "King of dates - jumbo juicy Medjool" },
    { parentSlug: "dates", name: "Safawi Dates", slug: "safawi-dates", imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500&auto=format&fit=crop&q=80", description: "Rich chewy semi-dry dark Safawi dates" },
    { parentSlug: "dates", name: "Sukkari Dates", slug: "sukkari-dates", imageUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=500&auto=format&fit=crop&q=80", description: "Sweet golden cone Sukkari dates" },

    // Spices
    { parentSlug: "spices", name: "Turmeric Powder", slug: "turmeric-powder", imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80", description: "Bright yellow high-curcumin stone ground turmeric" },
    { parentSlug: "spices", name: "Chili Powder", slug: "chili-powder", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", description: "Spicy natural red chili powder" },
    { parentSlug: "spices", name: "Cumin Powder", slug: "cumin-powder", imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=500&auto=format&fit=crop&q=80", description: "Roasted aroma cumin seed powder" },
    { parentSlug: "spices", name: "Garam Masala", slug: "garam-masala", imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", description: "14-spice royal Bangladeshi aromatic blend" },

    // Nuts & Seeds
    { parentSlug: "nuts-seeds", name: "Cashew Nuts", slug: "cashew-nuts", imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=500&auto=format&fit=crop&q=80", description: "Whole creamy roasted and raw cashew kernels" },
    { parentSlug: "nuts-seeds", name: "Almonds", slug: "almonds", imageUrl: "https://images.unsplash.com/photo-1508061252445-b95013cb7c5b?w=500&auto=format&fit=crop&q=80", description: "California jumbo nonpareil almonds" },
    { parentSlug: "nuts-seeds", name: "Chia Seeds", slug: "chia-seeds", imageUrl: "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=500&auto=format&fit=crop&q=80", description: "Omega-3 rich certified organic chia seeds" },
    { parentSlug: "nuts-seeds", name: "Walnuts", slug: "walnuts", imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80", description: "Brain-boosting raw Chilean walnut kernels" },

    // Organic Food
    { parentSlug: "organic-food", name: "Superfoods", slug: "superfoods", imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=500&auto=format&fit=crop&q=80", description: "Nutrient-dense spirulina, moringa, bee pollen" },
    { parentSlug: "organic-food", name: "Himalayan Pink Salt", slug: "pink-salt", imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=500&auto=format&fit=crop&q=80", description: "Unrefined 84-mineral organic rock salt" },
    { parentSlug: "organic-food", name: "Apple Cider Vinegar", slug: "apple-cider-vinegar", imageUrl: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=500&auto=format&fit=crop&q=80", description: "Raw unfiltered ACV with live Mother" },

    // Rice & Grains
    { parentSlug: "rice-grains", name: "Aromatic Rice", slug: "aromatic-rice", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", description: "Traditional Dinajpur Kalijira polao rice" },
    { parentSlug: "rice-grains", name: "Basmati Rice", slug: "basmati-rice", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", description: "Long grain aged royal Basmati rice" },
    { parentSlug: "rice-grains", name: "Brown & Red Rice", slug: "brown-red-rice", imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", description: "Unpolished diabetic-friendly wholesome grains" },

    // Beverages
    { parentSlug: "beverages", name: "Green Tea", slug: "green-tea", imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&auto=format&fit=crop&q=80", description: "Sreemangal organic estate whole leaf green tea" },
    { parentSlug: "beverages", name: "Masala Chai", slug: "masala-chai", imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80", description: "Aromatic spice-infused artisanal black tea" },
    { parentSlug: "beverages", name: "Coffee", slug: "coffee", imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=500&auto=format&fit=crop&q=80", description: "Medium and dark roasted premium Arabica beans" },

    // Snacks
    { parentSlug: "snacks", name: "Chanachur & Mixtures", slug: "chanachur-mixtures", imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500&auto=format&fit=crop&q=80", description: "Crunchy spicy garlic handmade chanachur" },
    { parentSlug: "snacks", name: "Dry Fruit Mix", slug: "dry-fruit-mix", imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=500&auto=format&fit=crop&q=80", description: "Energy-packed roasted nuts and berry blends" },
    { parentSlug: "snacks", name: "Traditional Sweets", slug: "traditional-sweets", imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500&auto=format&fit=crop&q=80", description: "Handmade Nakshi Pitha and Narkel Naru" },

    // Cooking Essentials
    { parentSlug: "cooking-essentials", name: "Brown Sugar & Jaggery", slug: "sugar-jaggery", imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=500&auto=format&fit=crop&q=80", description: "Pure date palm jaggery and unrefined brown sugar" },
    { parentSlug: "cooking-essentials", name: "Flour & Atta", slug: "flour-atta", imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", description: "Stone-ground whole wheat chakki atta" },
    { parentSlug: "cooking-essentials", name: "Vinegar & Seasonings", slug: "vinegar-seasonings", imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=500&auto=format&fit=crop&q=80", description: "Natural sugarcane vinegar and seasoning salts" },
  ];

  const subcategoryMap = new Map<string, mongoose.Types.ObjectId>();

  let subOrder = 1;
  for (const def of subcategoryDefs) {
    const parentId = categoryMap.get(def.parentSlug);
    if (!parentId) continue;

    const sub = await CategoryModel.findOneAndUpdate(
      { storeId, slug: def.slug },
      {
        $set: {
          storeId,
          name: def.name,
          nameEn: def.name,
          nameBn: def.name,
          slug: def.slug,
          imageUrl: def.imageUrl,
          description: def.description,
          descriptionEn: def.description,
          descriptionBn: def.description,
          parentId,
          active: true,
          featured: false,
          sortOrder: subOrder++,
        },
      },
      { upsert: true, new: true }
    );
    subcategoryMap.set(def.slug, sub._id as mongoose.Types.ObjectId);
  }
  console.log(`✅ [Seed] Upserted 35 Subcategories under parent categories.`);

  // ── 3. Seed 10 Realistic Brands ───────────────────────────────────────────
  const brandDefs = [
    {
      name: "Honeyraj",
      nameEn: "Honeyraj",
      nameBn: "হানিরাজ",
      slug: "honeyraj",
      logoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=300&auto=format&fit=crop&q=80",
      description: "Pioneer in wild Sundarban raw honey and therapeutic hive products.",
      website: "https://honeyraj.com.bd",
    },
    {
      name: "Khaijuri",
      nameEn: "Khaijuri",
      nameBn: "খাইজুরী",
      slug: "khaijuri",
      logoUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=300&auto=format&fit=crop&q=80",
      description: "Direct importer of premium authenticated Middle-Eastern dates.",
      website: "https://khaijuri.com.bd",
    },
    {
      name: "Glarevest",
      nameEn: "Glarevest",
      nameBn: "গ্লেয়ারভেস্ট",
      slug: "glarevest",
      logoUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=80",
      description: "Traditional wood-pressed cold extraction pure edible oils.",
      website: "https://glarevest.com",
    },
    {
      name: "Shomi",
      nameEn: "Shomi",
      nameBn: "শোমী ফুডস",
      slug: "shomi",
      logoUrl: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=300&auto=format&fit=crop&q=80",
      description: "Artisanal Bhatiari cow ghee and traditional Bangladeshi staples.",
      website: "https://shomi-foods.com",
    },
    {
      name: "Pure Harvest",
      nameEn: "Pure Harvest",
      nameBn: "পিওর হারভেস্ট",
      slug: "pure-harvest",
      logoUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=300&auto=format&fit=crop&q=80",
      description: "Certified organic chia seeds, superfoods, and raw nuts.",
      website: "https://pureharvestbd.com",
    },
    {
      name: "Deshi Naturals",
      nameEn: "Deshi Naturals",
      nameBn: "দেশি ন্যাচারালস",
      slug: "deshi-naturals",
      logoUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=300&auto=format&fit=crop&q=80",
      description: "Stone-ground village spices and authentic handcrafted chanachur.",
      website: "https://deshinaturals.com",
    },
    {
      name: "Green Valley",
      nameEn: "Green Valley",
      nameBn: "গ্রিন ভ্যালি",
      slug: "green-valley",
      logoUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=80",
      description: "Heritage aromatic polao rice, organic red rice, and whole pulses.",
      website: "https://greenvalleybd.com",
    },
    {
      name: "Tea Leaf Co",
      nameEn: "Tea Leaf Co",
      nameBn: "টি লিফ কোং",
      slug: "tea-leaf-co",
      logoUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=300&auto=format&fit=crop&q=80",
      description: "Sreemangal whole-leaf organic green teas and artisan masala blends.",
      website: "https://tealeaf.com.bd",
    },
    {
      name: "Crunch King",
      nameEn: "Crunch King",
      nameBn: "ক্রাঞ্চ কিং",
      slug: "crunch-king",
      logoUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=300&auto=format&fit=crop&q=80",
      description: "Famous gourmet spicy chanachur and roasted trail mix snacks.",
      website: "https://crunchkingbd.com",
    },
    {
      name: "Borno Agro",
      nameEn: "Borno Agro",
      nameBn: "বর্ণ এগ্রো",
      slug: "borno-agro",
      logoUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=300&auto=format&fit=crop&q=80",
      description: "Direct-from-farm unrefined organic brown sugar, honey, and jaggery.",
      website: "https://bornoagro.com",
    },
  ];

  const brandMap = new Map<string, mongoose.Types.ObjectId>();

  let bOrder = 1;
  for (const b of brandDefs) {
    const brand = await BrandModel.findOneAndUpdate(
      { storeId, slug: b.slug },
      {
        $set: {
          storeId,
          name: b.name,
          nameEn: b.nameEn,
          nameBn: b.nameBn,
          slug: b.slug,
          logoUrl: b.logoUrl,
          description: b.description,
          descriptionEn: b.description,
          descriptionBn: b.description,
          website: b.website,
          active: true,
          featured: true,
          sortOrder: bOrder++,
        },
      },
      { upsert: true, new: true }
    );
    brandMap.set(b.slug, brand._id as mongoose.Types.ObjectId);
  }
  console.log(`✅ [Seed] Upserted 10 Brands.`);

  // ── 4. Seed Exactly 100 Products ──────────────────────────────────────────
  const productsData = [
    // 1-12: Honey (12 items)
    {
      name: "Sundarban Wild Raw Honey 500g",
      slug: "sundarban-wild-raw-honey-500g",
      price: 850,
      comparePrice: 950,
      categorySlug: "honey",
      subSlug: "sundarban-honey",
      brandSlug: "honeyraj",
      stock: 45,
      featured: true,
      tags: ["Organic", "Raw", "Sundarban", "Best Seller", "Natural"],
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-SUN-500G",
      weight: 0.5,
      description: "Authentic wild honey harvested directly from the deep mangrove forest of Sundarbans by traditional Mawals.",
    },
    {
      name: "Sundarban Wild Raw Honey 1kg",
      slug: "sundarban-wild-raw-honey-1kg",
      price: 1650,
      comparePrice: 1850,
      categorySlug: "honey",
      subSlug: "sundarban-honey",
      brandSlug: "honeyraj",
      stock: 30,
      featured: true,
      tags: ["Organic", "Raw", "Sundarban", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-SUN-1KG",
      weight: 1.0,
      description: "Family size 1kg jar of unprocessed wild Sundarban raw honey.",
    },
    {
      name: "Natural Mustard Blossom Honey 500g",
      slug: "natural-mustard-blossom-honey-500g",
      price: 450,
      comparePrice: 520,
      categorySlug: "honey",
      subSlug: "raw-honey",
      brandSlug: "honeyraj",
      stock: 80,
      featured: false,
      tags: ["Natural", "Mustard", "Pure"],
      imageUrl: "https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-MUS-500G",
      weight: 0.5,
      description: "Delicately sweet honey collected during the winter mustard bloom across rural Bangladesh.",
    },
    {
      name: "Natural Mustard Blossom Honey 1kg",
      slug: "natural-mustard-blossom-honey-1kg",
      price: 850,
      comparePrice: 990,
      categorySlug: "honey",
      subSlug: "raw-honey",
      brandSlug: "honeyraj",
      stock: 60,
      featured: false,
      tags: ["Natural", "Mustard", "Pure"],
      imageUrl: "https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-MUS-1KG",
      weight: 1.0,
      description: "1kg pack of creamy crystallized natural mustard blossom honey.",
    },
    {
      name: "Black Seed Infused Medicinal Honey 500g",
      slug: "black-seed-infused-medicinal-honey-500g",
      price: 950,
      comparePrice: 1100,
      categorySlug: "honey",
      subSlug: "black-seed-honey",
      brandSlug: "honeyraj",
      stock: 35,
      featured: true,
      tags: ["Black Seed", "Kalijira", "Medicinal", "Immunity"],
      imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-BLK-500G",
      weight: 0.5,
      description: "Powerful natural immunity booster combining pure raw honey with Nigella Sativa (black seed) extract.",
    },
    {
      name: "Black Seed Infused Medicinal Honey 1kg",
      slug: "black-seed-infused-medicinal-honey-1kg",
      price: 1800,
      comparePrice: 2100,
      categorySlug: "honey",
      subSlug: "black-seed-honey",
      brandSlug: "honeyraj",
      stock: 20,
      featured: false,
      tags: ["Black Seed", "Medicinal", "Premium"],
      imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-BLK-1KG",
      weight: 1.0,
      description: "1kg value jar of therapeutic black seed honey for daily family wellness.",
    },
    {
      name: "Pure Litchi Blossom Honey 500g",
      slug: "pure-litchi-blossom-honey-500g",
      price: 550,
      comparePrice: 650,
      categorySlug: "honey",
      subSlug: "organic-honey",
      brandSlug: "pure-harvest",
      stock: 50,
      featured: false,
      tags: ["Litchi", "Floral", "Aromatic"],
      imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-LTC-500G",
      weight: 0.5,
      description: "Aromatic floral honey collected from the luscious litchi orchards of Dinajpur.",
    },
    {
      name: "Pure Litchi Blossom Honey 1kg",
      slug: "pure-litchi-blossom-honey-1kg",
      price: 1050,
      comparePrice: 1250,
      categorySlug: "honey",
      subSlug: "organic-honey",
      brandSlug: "pure-harvest",
      stock: 25,
      featured: false,
      tags: ["Litchi", "Floral", "Organic"],
      imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-LTC-1KG",
      weight: 1.0,
      description: "1kg jar of fragrant golden litchi flower honey.",
    },
    {
      name: "Organic Forest Honey Comb Jar 400g",
      slug: "organic-forest-honey-comb-jar-400g",
      price: 1200,
      comparePrice: 1450,
      categorySlug: "honey",
      subSlug: "raw-honey",
      brandSlug: "honeyraj",
      stock: 6, // Low stock
      featured: true,
      tags: ["Honeycomb", "Deluxe", "Limited"],
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-CMB-400G",
      weight: 0.4,
      description: "Pure whole natural honeycomb submerged in wild mountain honey.",
    },
    {
      name: "Sundarban Khalisha Blossom Honey 500g",
      slug: "sundarban-khalisha-blossom-honey-500g",
      price: 1100,
      comparePrice: 1300,
      categorySlug: "honey",
      subSlug: "sundarban-honey",
      brandSlug: "honeyraj",
      stock: 18,
      featured: false,
      tags: ["Sundarban", "Khalisha", "Exotic"],
      imageUrl: "https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-KHL-500G",
      weight: 0.5,
      description: "The rarest honey from Sundarbans, produced exclusively from Khalisha tree blossoms in early spring.",
    },
    {
      name: "Natural Coriander Blossom Honey 500g",
      slug: "natural-coriander-blossom-honey-500g",
      price: 650,
      comparePrice: 750,
      categorySlug: "honey",
      subSlug: "organic-honey",
      brandSlug: "pure-harvest",
      stock: 22,
      featured: false,
      tags: ["Coriander", "Digestion", "Herbal"],
      imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-COR-500G",
      weight: 0.5,
      description: "Rich amber honey known for soothing digestive properties.",
    },
    {
      name: "Royal Multi-Flora Mountain Honey 750g",
      slug: "royal-multi-flora-mountain-honey-750g",
      price: 1450,
      comparePrice: 1650,
      categorySlug: "honey",
      subSlug: "raw-honey",
      brandSlug: "honeyraj",
      stock: 15,
      featured: false,
      tags: ["Mountain", "Royal", "Multi-Flora"],
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "HNY-MTN-750G",
      weight: 0.75,
      description: "Complex floral nectar collected from pristine hill tract wildflower reserves.",
    },

    // 13-24: Oil & Ghee (12 items)
    {
      name: "Wood-Pressed Cold Pressed Mustard Oil 1L",
      slug: "wood-pressed-mustard-oil-1l",
      price: 380,
      comparePrice: 440,
      categorySlug: "oil-ghee",
      subSlug: "mustard-oil",
      brandSlug: "glarevest",
      stock: 120,
      featured: true,
      tags: ["Ghani Bhanga", "Mustard Oil", "Best Seller", "Pure"],
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-MUS-1L",
      weight: 1.0,
      description: "Traditional wooden Ghani extracted unrefined mustard oil with intense natural aroma and pungent taste.",
    },
    {
      name: "Wood-Pressed Mustard Oil 2L",
      slug: "wood-pressed-mustard-oil-2l",
      price: 740,
      comparePrice: 850,
      categorySlug: "oil-ghee",
      subSlug: "mustard-oil",
      brandSlug: "glarevest",
      stock: 75,
      featured: false,
      tags: ["Mustard Oil", "Ghani Bhanga", "Economy Pack"],
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-MUS-2L",
      weight: 2.0,
      description: "2 Liter value bottle of cold-pressed traditional Bangladeshi mustard oil.",
    },
    {
      name: "Premium Wood-Pressed Mustard Oil 5L Jar",
      slug: "premium-wood-pressed-mustard-oil-5l-jar",
      price: 1800,
      comparePrice: 2100,
      categorySlug: "oil-ghee",
      subSlug: "mustard-oil",
      brandSlug: "glarevest",
      stock: 40,
      featured: false,
      tags: ["Mustard Oil", "Bulk", "Family"],
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-MUS-5L",
      weight: 5.0,
      description: "Family size 5 Liter food-grade jar of chemical-free wood-pressed mustard oil.",
    },
    {
      name: "Organic Extra Virgin Olive Oil 500ml",
      slug: "organic-extra-virgin-olive-oil-500ml",
      price: 950,
      comparePrice: 1150,
      categorySlug: "oil-ghee",
      subSlug: "olive-oil",
      brandSlug: "organic-bangladesh",
      stock: 55,
      featured: true,
      tags: ["Olive Oil", "Extra Virgin", "Imported", "Heart Healthy"],
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-OLV-500ML",
      weight: 0.5,
      description: "First cold pressed unrefined Mediterranean extra virgin olive oil.",
    },
    {
      name: "Cold Pressed Extra Virgin Olive Oil 1L",
      slug: "cold-pressed-extra-virgin-olive-oil-1l",
      price: 1750,
      comparePrice: 2100,
      categorySlug: "oil-ghee",
      subSlug: "olive-oil",
      brandSlug: "organic-bangladesh",
      stock: 35,
      featured: false,
      tags: ["Olive Oil", "Extra Virgin", "Heart Healthy"],
      imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-OLV-1L",
      weight: 1.0,
      description: "1 Liter glass bottle of premium unfiltered extra virgin olive oil.",
    },
    {
      name: "Pure Bhatiari Cow Ghee 400g",
      slug: "pure-bhatiari-cow-ghee-400g",
      price: 920,
      comparePrice: 1050,
      categorySlug: "oil-ghee",
      subSlug: "pure-ghee",
      brandSlug: "shomi",
      stock: 65,
      featured: true,
      tags: ["Ghee", "Cow Milk", "Aromatic", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&auto=format&fit=crop&q=80",
      sku: "GHE-COW-400G",
      weight: 0.4,
      description: "Authentic golden Gawa Ghee slow-clarified from pasture-raised cow milk butter.",
    },
    {
      name: "Pure Bhatiari Cow Ghee 900g",
      slug: "pure-bhatiari-cow-ghee-900g",
      price: 1950,
      comparePrice: 2250,
      categorySlug: "oil-ghee",
      subSlug: "pure-ghee",
      brandSlug: "shomi",
      stock: 28,
      featured: true,
      tags: ["Ghee", "Deshi", "Premium"],
      imageUrl: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&auto=format&fit=crop&q=80",
      sku: "GHE-COW-900G",
      weight: 0.9,
      description: "Family size 900g glass jar of granular golden cow ghee.",
    },
    {
      name: "Organic Extra Virgin Coconut Oil 500ml",
      slug: "organic-extra-virgin-coconut-oil-500ml",
      price: 650,
      comparePrice: 780,
      categorySlug: "oil-ghee",
      subSlug: "coconut-oil",
      brandSlug: "glarevest",
      stock: 40,
      featured: false,
      tags: ["Coconut Oil", "Virgin", "Organic"],
      imageUrl: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-COC-500ML",
      weight: 0.5,
      description: "Cold-pressed from fresh organic coconut meat for cooking, hair, and skincare.",
    },
    {
      name: "Pure Sesame (Til) Cold Pressed Oil 250ml",
      slug: "pure-sesame-til-cold-pressed-oil-250ml",
      price: 320,
      comparePrice: 380,
      categorySlug: "oil-ghee",
      subSlug: "mustard-oil",
      brandSlug: "glarevest",
      stock: 30,
      featured: false,
      tags: ["Til Oil", "Sesame", "Herbal"],
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-SES-250ML",
      weight: 0.25,
      description: "Nutty and nutritious unrefined black sesame oil.",
    },
    {
      name: "Cold Pressed Black Seed (Kalijira) Oil 100ml",
      slug: "cold-pressed-black-seed-kalijira-oil-100ml",
      price: 350,
      comparePrice: 420,
      categorySlug: "oil-ghee",
      subSlug: "mustard-oil",
      brandSlug: "honeyraj",
      stock: 4, // Low stock
      featured: true,
      tags: ["Kalijira", "Black Seed Oil", "Immunity"],
      imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-BLK-100ML",
      weight: 0.1,
      description: "100% pure therapeutic grade cold-pressed black seed oil in amber glass bottle.",
    },
    {
      name: "Pure Buffalo Milk Deshi Ghee 450g",
      slug: "pure-buffalo-milk-deshi-ghee-450g",
      price: 1100,
      comparePrice: 1280,
      categorySlug: "oil-ghee",
      subSlug: "pure-ghee",
      brandSlug: "shomi",
      stock: 14,
      featured: false,
      tags: ["Buffalo Ghee", "Deshi", "Rich"],
      imageUrl: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&auto=format&fit=crop&q=80",
      sku: "GHE-BUF-450G",
      weight: 0.45,
      description: "Thick, creamy white clarified butter made from rich deshi buffalo milk.",
    },
    {
      name: "Cold Pressed Almond Oil 100ml",
      slug: "cold-pressed-almond-oil-100ml",
      price: 580,
      comparePrice: 680,
      categorySlug: "oil-ghee",
      subSlug: "olive-oil",
      brandSlug: "pure-harvest",
      stock: 20,
      featured: false,
      tags: ["Almond Oil", "Pure", "Wellness"],
      imageUrl: "https://images.unsplash.com/photo-1508061252445-b95013cb7c5b?w=800&auto=format&fit=crop&q=80",
      sku: "OIL-ALM-100ML",
      weight: 0.1,
      description: "Pure sweet almond oil extracted through cold pressing for culinary and beauty applications.",
    },

    // 25-34: Dates (10 items)
    {
      name: "Premium Madinah Ajwa Dates 500g",
      slug: "premium-madinah-ajwa-dates-500g",
      price: 1250,
      comparePrice: 1450,
      categorySlug: "dates",
      subSlug: "ajwa-dates",
      brandSlug: "khaijuri",
      stock: 70,
      featured: true,
      tags: ["Ajwa", "Madinah", "Dates", "Best Seller", "Holy"],
      imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-AJW-500G",
      weight: 0.5,
      description: "Authentic dark textured Ajwa dates sourced directly from certified orchards in Madinah Al-Munawwarah.",
    },
    {
      name: "Premium Madinah Ajwa Dates 1kg",
      slug: "premium-madinah-ajwa-dates-1kg",
      price: 2400,
      comparePrice: 2800,
      categorySlug: "dates",
      subSlug: "ajwa-dates",
      brandSlug: "khaijuri",
      stock: 45,
      featured: true,
      tags: ["Ajwa", "Dates", "Madinah", "Premium"],
      imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-AJW-1KG",
      weight: 1.0,
      description: "1kg luxury gift pack of fresh soft Ajwa dates.",
    },
    {
      name: "Jumbo Palestinian Medjool Dates 500g",
      slug: "jumbo-palestinian-medjool-dates-500g",
      price: 1100,
      comparePrice: 1300,
      categorySlug: "dates",
      subSlug: "medjool-dates",
      brandSlug: "khaijuri",
      stock: 50,
      featured: true,
      tags: ["Medjool", "Jumbo", "Dates", "Sweet"],
      imageUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-MED-500G",
      weight: 0.5,
      description: "Large, luscious, caramel-flavored Medjool dates with tender skin.",
    },
    {
      name: "Jumbo Palestinian Medjool Dates 1kg",
      slug: "jumbo-palestinian-medjool-dates-1kg",
      price: 2100,
      comparePrice: 2500,
      categorySlug: "dates",
      subSlug: "medjool-dates",
      brandSlug: "khaijuri",
      stock: 35,
      featured: false,
      tags: ["Medjool", "Dates", "Jumbo"],
      imageUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-MED-1KG",
      weight: 1.0,
      description: "1kg box of premium jumbo Medjool dates.",
    },
    {
      name: "Soft Saudi Safawi Dates 500g",
      slug: "soft-saudi-safawi-dates-500g",
      price: 650,
      comparePrice: 750,
      categorySlug: "dates",
      subSlug: "safawi-dates",
      brandSlug: "khaijuri",
      stock: 60,
      featured: false,
      tags: ["Safawi", "Dates", "Healthy"],
      imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-SAF-500G",
      weight: 0.5,
      description: "Chewy and dark Safawi dates rich in dietary fibers and natural minerals.",
    },
    {
      name: "Soft Saudi Safawi Dates 1kg",
      slug: "soft-saudi-safawi-dates-1kg",
      price: 1250,
      comparePrice: 1450,
      categorySlug: "dates",
      subSlug: "safawi-dates",
      brandSlug: "khaijuri",
      stock: 40,
      featured: false,
      tags: ["Safawi", "Dates", "Value"],
      imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-SAF-1KG",
      weight: 1.0,
      description: "1kg value box of fresh Safawi dates from Saudi Arabia.",
    },
    {
      name: "Premium Mabroom Dates 500g",
      slug: "premium-mabroom-dates-500g",
      price: 850,
      comparePrice: 990,
      categorySlug: "dates",
      subSlug: "safawi-dates",
      brandSlug: "khaijuri",
      stock: 35,
      featured: false,
      tags: ["Mabroom", "Dates", "Elongated"],
      imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-MAB-500G",
      weight: 0.5,
      description: "Slender, firm, and subtly sweet Mabroom dates from Madinah.",
    },
    {
      name: "Premium Sukkari Cone Dates 1kg",
      slug: "premium-sukkari-cone-dates-1kg",
      price: 950,
      comparePrice: 1100,
      categorySlug: "dates",
      subSlug: "sukkari-dates",
      brandSlug: "khaijuri",
      stock: 55,
      featured: true,
      tags: ["Sukkari", "Dates", "Sweet", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-SUK-1KG",
      weight: 1.0,
      description: "Melt-in-the-mouth golden Sukkari cone dates loved across the Middle East.",
    },
    {
      name: "Royal Amber Dates 500g",
      slug: "royal-amber-dates-500g",
      price: 1350,
      comparePrice: 1600,
      categorySlug: "dates",
      subSlug: "ajwa-dates",
      brandSlug: "khaijuri",
      stock: 5, // Low stock
      featured: false,
      tags: ["Amber", "Royal", "Dates", "Exotic"],
      imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-AMB-500G",
      weight: 0.5,
      description: "One of the largest date varieties, prized for its soft flesh and refined aroma.",
    },
    {
      name: "Fresh Mariam (Kalmi) Dates 1kg",
      slug: "fresh-mariam-kalmi-dates-1kg",
      price: 800,
      comparePrice: 950,
      categorySlug: "dates",
      subSlug: "safawi-dates",
      brandSlug: "khaijuri",
      stock: 65,
      featured: false,
      tags: ["Mariam", "Kalmi", "Dates"],
      imageUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=800&auto=format&fit=crop&q=80",
      sku: "DAT-MAR-1KG",
      weight: 1.0,
      description: "Popular Bangladeshi favorite soft Mariam dates for daily energy.",
    },

    // 35-44: Spices (10 items)
    {
      name: "Organic Stone-Ground Turmeric Powder 200g",
      slug: "organic-stone-ground-turmeric-powder-200g",
      price: 120,
      comparePrice: 150,
      categorySlug: "spices",
      subSlug: "turmeric-powder",
      brandSlug: "deshi-naturals",
      stock: 150,
      featured: true,
      tags: ["Turmeric", "Organic", "Stone Ground", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-TUR-200G",
      weight: 0.2,
      description: "Bright natural turmeric powder milled slowly on stone to retain curcumin content.",
    },
    {
      name: "Organic Stone-Ground Turmeric Powder 500g",
      slug: "organic-stone-ground-turmeric-powder-500g",
      price: 280,
      comparePrice: 340,
      categorySlug: "spices",
      subSlug: "turmeric-powder",
      brandSlug: "deshi-naturals",
      stock: 90,
      featured: false,
      tags: ["Turmeric", "Organic", "Economy"],
      imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-TUR-500G",
      weight: 0.5,
      description: "500g pantry pouch of natural Bangladeshi turmeric powder.",
    },
    {
      name: "Pure Hand-Pounded Red Chili Powder 200g",
      slug: "pure-hand-pounded-red-chili-powder-200g",
      price: 140,
      comparePrice: 170,
      categorySlug: "spices",
      subSlug: "chili-powder",
      brandSlug: "deshi-naturals",
      stock: 120,
      featured: false,
      tags: ["Chili", "Spicy", "Deshi"],
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-CHL-200G",
      weight: 0.2,
      description: "Spicy and vibrant red chili powder made from sun-dried Bangladeshi chillies.",
    },
    {
      name: "Pure Hand-Pounded Red Chili Powder 500g",
      slug: "pure-hand-pounded-red-chili-powder-500g",
      price: 320,
      comparePrice: 380,
      categorySlug: "spices",
      subSlug: "chili-powder",
      brandSlug: "deshi-naturals",
      stock: 75,
      featured: false,
      tags: ["Chili", "Spicy"],
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-CHL-500G",
      weight: 0.5,
      description: "500g bulk pouch of unadulterated red chili powder.",
    },
    {
      name: "Premium Roasted Cumin (Jeera) Powder 150g",
      slug: "premium-roasted-cumin-jeera-powder-150g",
      price: 180,
      comparePrice: 220,
      categorySlug: "spices",
      subSlug: "cumin-powder",
      brandSlug: "deshi-naturals",
      stock: 80,
      featured: false,
      tags: ["Jeera", "Cumin", "Aromatic"],
      imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-JIR-150G",
      weight: 0.15,
      description: "Slowly dry-roasted cumin seeds finely ground for rich aroma in curries.",
    },
    {
      name: "Fresh Coriander (Dhania) Powder 200g",
      slug: "fresh-coriander-dhania-powder-200g",
      price: 110,
      comparePrice: 140,
      categorySlug: "spices",
      subSlug: "turmeric-powder",
      brandSlug: "deshi-naturals",
      stock: 95,
      featured: false,
      tags: ["Dhania", "Coriander"],
      imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-DHN-200G",
      weight: 0.2,
      description: "Naturally dried whole coriander seeds ground without synthetic additives.",
    },
    {
      name: "Shahi Special Royal Garam Masala 100g",
      slug: "shahi-special-royal-garam-masala-100g",
      price: 250,
      comparePrice: 300,
      categorySlug: "spices",
      subSlug: "garam-masala",
      brandSlug: "shomi",
      stock: 60,
      featured: true,
      tags: ["Garam Masala", "Shahi", "Royal", "Secret Blend"],
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-GRM-100G",
      weight: 0.1,
      description: "Master blend of 14 exotic whole spices for royal biryani, korma, and roast.",
    },
    {
      name: "Pure Cinnamon (Daruchini) Sticks 100g",
      slug: "pure-cinnamon-daruchini-sticks-100g",
      price: 190,
      comparePrice: 230,
      categorySlug: "spices",
      subSlug: "garam-masala",
      brandSlug: "deshi-naturals",
      stock: 45,
      featured: false,
      tags: ["Cinnamon", "Daruchini", "Whole Spice"],
      imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-CIN-100G",
      weight: 0.1,
      description: "High quality aromatic whole cinnamon barks.",
    },
    {
      name: "Green Cardamom (Elachi) Jumbo 50g",
      slug: "green-cardamom-elachi-jumbo-50g",
      price: 350,
      comparePrice: 420,
      categorySlug: "spices",
      subSlug: "garam-masala",
      brandSlug: "shomi",
      stock: 7, // Low stock
      featured: false,
      tags: ["Cardamom", "Elachi", "Jumbo"],
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-ELA-50G",
      weight: 0.05,
      description: "Large 8mm bold green cardamom pods bursting with essential aroma oils.",
    },
    {
      name: "Whole Black Pepper (Golmorich) 100g",
      slug: "whole-black-pepper-golmorich-100g",
      price: 160,
      comparePrice: 190,
      categorySlug: "spices",
      subSlug: "garam-masala",
      brandSlug: "deshi-naturals",
      stock: 50,
      featured: false,
      tags: ["Black Pepper", "Golmorich"],
      imageUrl: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80",
      sku: "SPC-BLK-100G",
      weight: 0.1,
      description: "Sun-dried robust black peppercorns from trusted farms.",
    },

    // 45-54: Nuts & Seeds (10 items)
    {
      name: "Premium W320 Whole Cashew Nuts 500g",
      slug: "premium-w320-whole-cashew-nuts-500g",
      price: 750,
      comparePrice: 890,
      categorySlug: "nuts-seeds",
      subSlug: "cashew-nuts",
      brandSlug: "pure-harvest",
      stock: 85,
      featured: true,
      tags: ["Cashew", "Kaju", "Nuts", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      sku: "NUT-CSH-500G",
      weight: 0.5,
      description: "Jumbo Grade W320 whole white cashew kernels with natural sweet crunch.",
    },
    {
      name: "Roasted & Lightly Salted Cashew Nuts 250g",
      slug: "roasted-lightly-salted-cashew-nuts-250g",
      price: 420,
      comparePrice: 490,
      categorySlug: "nuts-seeds",
      subSlug: "cashew-nuts",
      brandSlug: "pure-harvest",
      stock: 60,
      featured: false,
      tags: ["Cashew", "Roasted", "Snack"],
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      sku: "NUT-RCS-250G",
      weight: 0.25,
      description: "Oven-roasted crispy cashews seasoned lightly with pink rock salt.",
    },
    {
      name: "California Jumbo Almonds 500g",
      slug: "california-jumbo-almonds-500g",
      price: 680,
      comparePrice: 800,
      categorySlug: "nuts-seeds",
      subSlug: "almonds",
      brandSlug: "pure-harvest",
      stock: 90,
      featured: true,
      tags: ["Almonds", "Badam", "Nuts", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1508061252445-b95013cb7c5b?w=800&auto=format&fit=crop&q=80",
      sku: "NUT-ALM-500G",
      weight: 0.5,
      description: "Nutritious nonpareil California almonds rich in Vitamin E and antioxidants.",
    },
    {
      name: "Raw Organic California Almonds 1kg",
      slug: "raw-organic-california-almonds-1kg",
      price: 1300,
      comparePrice: 1550,
      categorySlug: "nuts-seeds",
      subSlug: "almonds",
      brandSlug: "pure-harvest",
      stock: 40,
      featured: false,
      tags: ["Almonds", "Organic", "Economy"],
      imageUrl: "https://images.unsplash.com/photo-1508061252445-b95013cb7c5b?w=800&auto=format&fit=crop&q=80",
      sku: "NUT-ALM-1KG",
      weight: 1.0,
      description: "1kg value pack of raw whole almonds.",
    },
    {
      name: "Chilean Premium Raw Walnut Kernels 250g",
      slug: "chilean-premium-raw-walnut-kernels-250g",
      price: 450,
      comparePrice: 530,
      categorySlug: "nuts-seeds",
      subSlug: "walnuts",
      brandSlug: "pure-harvest",
      stock: 35,
      featured: false,
      tags: ["Walnuts", "Akrot", "Brain Food"],
      imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80",
      sku: "NUT-WLN-250G",
      weight: 0.25,
      description: "Light amber walnut halves packed with Omega-3 fatty acids.",
    },
    {
      name: "Iranian Green Pistachios Roasted 200g",
      slug: "iranian-green-pistachios-roasted-200g",
      price: 550,
      comparePrice: 650,
      categorySlug: "nuts-seeds",
      subSlug: "cashew-nuts",
      brandSlug: "nature-basket",
      stock: 8, // Low stock
      featured: false,
      tags: ["Pistachio", "Pesta", "Premium"],
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      sku: "NUT-PST-200G",
      weight: 0.2,
      description: "In-shell salted roasted pistachios with signature green kernels.",
    },
    {
      name: "Certified Organic Chia Seeds 250g",
      slug: "certified-organic-chia-seeds-250g",
      price: 280,
      comparePrice: 340,
      categorySlug: "nuts-seeds",
      subSlug: "chia-seeds",
      brandSlug: "organic-bangladesh",
      stock: 110,
      featured: true,
      tags: ["Chia Seed", "Superfood", "Diet", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80",
      sku: "SED-CHI-250G",
      weight: 0.25,
      description: "100% certified organic black chia seeds for weight management and daily smoothies.",
    },
    {
      name: "Certified Organic Chia Seeds 500g",
      slug: "certified-organic-chia-seeds-500g",
      price: 520,
      comparePrice: 650,
      categorySlug: "nuts-seeds",
      subSlug: "chia-seeds",
      brandSlug: "organic-bangladesh",
      stock: 70,
      featured: false,
      tags: ["Chia Seed", "Organic"],
      imageUrl: "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80",
      sku: "SED-CHI-500G",
      weight: 0.5,
      description: "500g value pouch of clean organic chia seeds.",
    },
    {
      name: "Raw Pumpkin Seeds (Grade A) 200g",
      slug: "raw-pumpkin-seeds-grade-a-200g",
      price: 260,
      comparePrice: 310,
      categorySlug: "nuts-seeds",
      subSlug: "chia-seeds",
      brandSlug: "pure-harvest",
      stock: 45,
      featured: false,
      tags: ["Pumpkin Seeds", "Zinc", "Prostate Health"],
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      sku: "SED-PMK-200G",
      weight: 0.2,
      description: "Green shelled pumpkin seeds loaded with zinc and healthy magnesium.",
    },
    {
      name: "Natural Sunflower Seeds 250g",
      slug: "natural-sunflower-seeds-250g",
      price: 190,
      comparePrice: 230,
      categorySlug: "nuts-seeds",
      subSlug: "chia-seeds",
      brandSlug: "pure-harvest",
      stock: 50,
      featured: false,
      tags: ["Sunflower Seeds", "Healthy Snack"],
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      sku: "SED-SUN-250G",
      weight: 0.25,
      description: "Crispy de-hulled raw sunflower seeds for healthy snacking.",
    },

    // 55-64: Organic Food (10 items)
    {
      name: "Raw Unfiltered Apple Cider Vinegar with Mother 500ml",
      slug: "raw-unfiltered-apple-cider-vinegar-with-mother-500ml",
      price: 650,
      comparePrice: 780,
      categorySlug: "organic-food",
      subSlug: "apple-cider-vinegar",
      brandSlug: "organic-bangladesh",
      stock: 75,
      featured: true,
      tags: ["ACV", "Apple Cider Vinegar", "With Mother", "Detox", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-ACV-500ML",
      weight: 0.5,
      description: "Raw, unfiltered and unpasteurized ACV crafted from organic apples with active probiotic mother.",
    },
    {
      name: "Organic Pink Himalayan Rock Salt Fine 500g",
      slug: "organic-pink-himalayan-rock-salt-fine-500g",
      price: 150,
      comparePrice: 180,
      categorySlug: "organic-food",
      subSlug: "pink-salt",
      brandSlug: "organic-bangladesh",
      stock: 130,
      featured: false,
      tags: ["Pink Salt", "Himalayan", "Mineral Salt"],
      imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-SLT-500G",
      weight: 0.5,
      description: "Pure ancient Himalayan crystal salt containing 84 natural trace minerals.",
    },
    {
      name: "Organic Pink Himalayan Rock Salt Coarse 1kg",
      slug: "organic-pink-himalayan-rock-salt-coarse-1kg",
      price: 280,
      comparePrice: 340,
      categorySlug: "organic-food",
      subSlug: "pink-salt",
      brandSlug: "organic-bangladesh",
      stock: 80,
      featured: false,
      tags: ["Pink Salt", "Coarse"],
      imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-SLT-1KG",
      weight: 1.0,
      description: "1kg pouch of coarse pink salt crystals suitable for salt grinders and cooking.",
    },
    {
      name: "Pure Organic Spirulina Powder 100g",
      slug: "pure-organic-spirulina-powder-100g",
      price: 450,
      comparePrice: 550,
      categorySlug: "organic-food",
      subSlug: "superfoods",
      brandSlug: "organic-bangladesh",
      stock: 6, // Low stock
      featured: false,
      tags: ["Spirulina", "Superfood", "Protein"],
      imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-SPI-100G",
      weight: 0.1,
      description: "Blue-green algae superfood powder packed with plant protein, iron, and antioxidants.",
    },
    {
      name: "Organic Moringa Leaf Powder (Sojne Pata) 150g",
      slug: "organic-moringa-leaf-powder-sojne-pata-150g",
      price: 220,
      comparePrice: 280,
      categorySlug: "organic-food",
      subSlug: "superfoods",
      brandSlug: "organic-bangladesh",
      stock: 60,
      featured: true,
      tags: ["Moringa", "Sojne", "Immunity", "Superfood"],
      imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-MOR-150G",
      weight: 0.15,
      description: "Miracle tree moringa leaves shade-dried and pulverized into nutrient rich green powder.",
    },
    {
      name: "Pure Natural Bee Pollen Granules 150g",
      slug: "pure-natural-bee-pollen-granules-150g",
      price: 680,
      comparePrice: 820,
      categorySlug: "organic-food",
      subSlug: "superfoods",
      brandSlug: "honeyraj",
      stock: 25,
      featured: false,
      tags: ["Bee Pollen", "Energy", "Superfood"],
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-POL-150G",
      weight: 0.15,
      description: "Golden flower pollen granules harvested gently by honeybees.",
    },
    {
      name: "Organic Cold Extracted Flaxseed Oil 250ml",
      slug: "organic-cold-extracted-flaxseed-oil-250ml",
      price: 390,
      comparePrice: 470,
      categorySlug: "organic-food",
      subSlug: "superfoods",
      brandSlug: "glarevest",
      stock: 30,
      featured: false,
      tags: ["Flaxseed", "Tishi", "Omega-3"],
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-FLX-250ML",
      weight: 0.25,
      description: "Raw unrefined flaxseed oil providing essential plant Omega-3 fatty acids.",
    },
    {
      name: "Pure Organic Virgin Coconut Flour 500g",
      slug: "pure-organic-virgin-coconut-flour-500g",
      price: 290,
      comparePrice: 350,
      categorySlug: "organic-food",
      subSlug: "superfoods",
      brandSlug: "pure-harvest",
      stock: 40,
      featured: false,
      tags: ["Coconut Flour", "Keto", "Gluten Free"],
      imageUrl: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-COC-500G",
      weight: 0.5,
      description: "Low-carb, high-fiber gluten free flour for keto and healthy baking.",
    },
    {
      name: "Raw Unprocessed Wheatgrass Powder 100g",
      slug: "raw-unprocessed-wheatgrass-powder-100g",
      price: 380,
      comparePrice: 460,
      categorySlug: "organic-food",
      subSlug: "superfoods",
      brandSlug: "organic-bangladesh",
      stock: 20,
      featured: false,
      tags: ["Wheatgrass", "Chlorophyll", "Detox"],
      imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-WHT-100G",
      weight: 0.1,
      description: "Young green wheatgrass leaves harvested at peak nutritional density.",
    },
    {
      name: "Organic Ashwagandha Root Powder 150g",
      slug: "organic-ashwagandha-root-powder-150g",
      price: 320,
      comparePrice: 390,
      categorySlug: "organic-food",
      subSlug: "superfoods",
      brandSlug: "organic-bangladesh",
      stock: 35,
      featured: false,
      tags: ["Ashwagandha", "Stress Relief", "Ayurvedic"],
      imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop&q=80",
      sku: "ORG-ASH-150G",
      weight: 0.15,
      description: "Natural adaptogenic root powder supporting calm mental focus and physical vitality.",
    },

    // 65-73: Rice & Grains (9 items)
    {
      name: "Premium Long Grain Royal Basmati Rice 5kg",
      slug: "premium-long-grain-royal-basmati-rice-5kg",
      price: 1450,
      comparePrice: 1700,
      categorySlug: "rice-grains",
      subSlug: "basmati-rice",
      brandSlug: "green-valley",
      stock: 55,
      featured: true,
      tags: ["Basmati", "Rice", "Biryani", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "RIC-BAS-5KG",
      weight: 5.0,
      description: "Extra long grain aged Basmati rice with exquisite aroma, perfect for gourmet biryani and pulao.",
    },
    {
      name: "Traditional Dinajpur Kalijira Aromatic Polao Rice 1kg",
      slug: "traditional-dinajpur-kalijira-aromatic-polao-rice-1kg",
      price: 180,
      comparePrice: 220,
      categorySlug: "rice-grains",
      subSlug: "aromatic-rice",
      brandSlug: "green-valley",
      stock: 120,
      featured: true,
      tags: ["Kalijira", "Polao Rice", "Aromatic", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "RIC-KLJ-1KG",
      weight: 1.0,
      description: "Small grain heritage Kalijira aromatic rice grown in the fertile soils of Dinajpur.",
    },
    {
      name: "Traditional Dinajpur Kalijira Polao Rice 5kg",
      slug: "traditional-dinajpur-kalijira-polao-rice-5kg",
      price: 850,
      comparePrice: 1000,
      categorySlug: "rice-grains",
      subSlug: "aromatic-rice",
      brandSlug: "green-valley",
      stock: 60,
      featured: false,
      tags: ["Kalijira", "Aromatic", "Economy"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "RIC-KLJ-5KG",
      weight: 5.0,
      description: "5kg bag of authentic Dinajpur polao rice.",
    },
    {
      name: "Organic Unpolished Red Rice 2kg",
      slug: "organic-unpolished-red-rice-2kg",
      price: 260,
      comparePrice: 310,
      categorySlug: "rice-grains",
      subSlug: "brown-red-rice",
      brandSlug: "green-valley",
      stock: 45,
      featured: true,
      tags: ["Red Rice", "Lal Chaal", "Unpolished", "Organic"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "RIC-RED-2KG",
      weight: 2.0,
      description: "Pesticide-free traditional Bangladeshi unpolished red rice loaded with natural bran.",
    },
    {
      name: "Premium Organic Brown Rice 2kg",
      slug: "premium-organic-brown-rice-2kg",
      price: 240,
      comparePrice: 290,
      categorySlug: "rice-grains",
      subSlug: "brown-red-rice",
      brandSlug: "green-valley",
      stock: 50,
      featured: false,
      tags: ["Brown Rice", "Diabetic Friendly", "Organic"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "RIC-BRN-2KG",
      weight: 2.0,
      description: "Wholesome brown rice with intact germ and bran for steady glycemic control.",
    },
    {
      name: "Premium Miniket Polished Rice 25kg Bag",
      slug: "premium-miniket-polished-rice-25kg-bag",
      price: 1850,
      comparePrice: 2050,
      categorySlug: "rice-grains",
      subSlug: "aromatic-rice",
      brandSlug: "green-valley",
      stock: 30,
      featured: false,
      tags: ["Miniket", "Daily Rice", "Bulk"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "RIC-MIN-25KG",
      weight: 25.0,
      description: "Clean, silky, premium sorted Miniket rice for daily family meals.",
    },
    {
      name: "Pure Deshi Nazirshail Premium Rice 5kg",
      slug: "pure-deshi-nazirshail-premium-rice-5kg",
      price: 420,
      comparePrice: 480,
      categorySlug: "rice-grains",
      subSlug: "aromatic-rice",
      brandSlug: "green-valley",
      stock: 40,
      featured: false,
      tags: ["Nazirshail", "Deshi Rice"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "RIC-NZR-5KG",
      weight: 5.0,
      description: "Firm non-sticky long grain Nazirshail rice.",
    },
    {
      name: "Organic Rolled Oats (Gluten-Free) 500g",
      slug: "organic-rolled-oats-gluten-free-500g",
      price: 320,
      comparePrice: 390,
      categorySlug: "rice-grains",
      subSlug: "brown-red-rice",
      brandSlug: "pure-harvest",
      stock: 65,
      featured: false,
      tags: ["Oats", "Breakfast", "Fiber"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "GRN-OAT-500G",
      weight: 0.5,
      description: "Thick whole rolled whole oats for breakfast oatmeal and healthy baking.",
    },
    {
      name: "White Quinoa Seeds (Grade A) 500g",
      slug: "white-quinoa-seeds-grade-a-500g",
      price: 550,
      comparePrice: 660,
      categorySlug: "rice-grains",
      subSlug: "brown-red-rice",
      brandSlug: "pure-harvest",
      stock: 9, // Low stock
      featured: false,
      tags: ["Quinoa", "Supergrain", "Protein"],
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
      sku: "GRN-QNA-500G",
      weight: 0.5,
      description: "Pre-washed complete protein supergrain imported from the Andes.",
    },

    // 74-81: Beverages (8 items)
    {
      name: "Sreemangal Premium Organic Green Tea 100g",
      slug: "sreemangal-premium-organic-green-tea-100g",
      price: 220,
      comparePrice: 270,
      categorySlug: "beverages",
      subSlug: "green-tea",
      brandSlug: "nature-basket",
      stock: 90,
      featured: true,
      tags: ["Green Tea", "Sreemangal", "Antioxidants", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-GRN-100G",
      weight: 0.1,
      description: "Hand-picked whole leaf green tea from the misty slopes of Sreemangal tea estates.",
    },
    {
      name: "Sreemangal CTC Premium Black Tea 500g",
      slug: "sreemangal-ctc-premium-black-tea-500g",
      price: 290,
      comparePrice: 350,
      categorySlug: "beverages",
      subSlug: "green-tea",
      brandSlug: "nature-basket",
      stock: 110,
      featured: true,
      tags: ["Black Tea", "Cha", "Daily Tea", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-BLK-500G",
      weight: 0.5,
      description: "Rich liquor and bold malty taste for the authentic cup of Bangladeshi milk tea.",
    },
    {
      name: "Artisan Royal Masala Chai Blend 150g",
      slug: "artisan-royal-masala-chai-blend-150g",
      price: 340,
      comparePrice: 410,
      categorySlug: "beverages",
      subSlug: "masala-chai",
      brandSlug: "nature-basket",
      stock: 45,
      featured: true,
      tags: ["Masala Chai", "Spiced Tea", "Winter Special"],
      imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-MSL-150G",
      weight: 0.15,
      description: "Hand-blended black tea with cinnamon, cardamom, clove, ginger, and nutmeg.",
    },
    {
      name: "Premium Arabica Medium Roast Coffee Beans 250g",
      slug: "premium-arabica-medium-roast-coffee-beans-250g",
      price: 650,
      comparePrice: 790,
      categorySlug: "beverages",
      subSlug: "coffee",
      brandSlug: "nature-basket",
      stock: 35,
      featured: false,
      tags: ["Coffee", "Arabica", "Beans"],
      imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-COF-250G",
      weight: 0.25,
      description: "100% Arabica whole coffee beans with chocolate and caramel notes.",
    },
    {
      name: "Dark Roast Espresso Ground Coffee 250g",
      slug: "dark-roast-espresso-ground-coffee-250g",
      price: 620,
      comparePrice: 750,
      categorySlug: "beverages",
      subSlug: "coffee",
      brandSlug: "nature-basket",
      stock: 25,
      featured: false,
      tags: ["Coffee", "Dark Roast", "Ground"],
      imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-DRK-250G",
      weight: 0.25,
      description: "Intense dark roasted finely ground coffee for espresso and moka pot.",
    },
    {
      name: "Organic Herbal Chamomile Whole Flower Tea 50g",
      slug: "organic-herbal-chamomile-whole-flower-tea-50g",
      price: 380,
      comparePrice: 460,
      categorySlug: "beverages",
      subSlug: "green-tea",
      brandSlug: "nature-basket",
      stock: 5, // Low stock
      featured: false,
      tags: ["Chamomile", "Sleep Tea", "Caffeine Free"],
      imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-CHM-50G",
      weight: 0.05,
      description: "Calming caffeine-free herbal tea brewed from whole German chamomile flowers.",
    },
    {
      name: "Hibiscus Herbal Crimson Flower Tea 75g",
      slug: "hibiscus-herbal-crimson-flower-tea-75g",
      price: 280,
      comparePrice: 340,
      categorySlug: "beverages",
      subSlug: "green-tea",
      brandSlug: "nature-basket",
      stock: 30,
      featured: false,
      tags: ["Hibiscus", "Vitamin C", "Herbal"],
      imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-HBC-75G",
      weight: 0.075,
      description: "Tart and refreshing crimson infusion rich in natural Vitamin C.",
    },
    {
      name: "Natural Roasted Barley Malt Health Drink 400g",
      slug: "natural-roasted-barley-malt-health-drink-400g",
      price: 450,
      comparePrice: 540,
      categorySlug: "beverages",
      subSlug: "masala-chai",
      brandSlug: "nature-basket",
      stock: 40,
      featured: false,
      tags: ["Malt", "Health Drink", "Barley"],
      imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80",
      sku: "BEV-MLT-400G",
      weight: 0.4,
      description: "Nutritious roasted malt and grain beverage powder for wholesome family drinks.",
    },

    // 82-90: Snacks (9 items)
    {
      name: "Special Spicy Garlic Chanachur 500g",
      slug: "special-spicy-garlic-chanachur-500g",
      price: 160,
      comparePrice: 190,
      categorySlug: "snacks",
      subSlug: "chanachur-mixtures",
      brandSlug: "deshi-naturals",
      stock: 140,
      featured: true,
      tags: ["Chanachur", "Garlic", "Spicy", "Deshi Snack", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-CHN-500G",
      weight: 0.5,
      description: "Crispy savory snack mix with fried garlic flakes, peanuts, and traditional spices.",
    },
    {
      name: "Special Spicy Garlic Chanachur 1kg Jar",
      slug: "special-spicy-garlic-chanachur-1kg-jar",
      price: 300,
      comparePrice: 360,
      categorySlug: "snacks",
      subSlug: "chanachur-mixtures",
      brandSlug: "deshi-naturals",
      stock: 75,
      featured: false,
      tags: ["Chanachur", "Bulk Jar"],
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-CHN-1KG",
      weight: 1.0,
      description: "1kg airtight jar of crunchy garlic chanachur.",
    },
    {
      name: "Oven-Roasted Salted Peanuts 300g",
      slug: "oven-roasted-salted-peanuts-300g",
      price: 140,
      comparePrice: 170,
      categorySlug: "snacks",
      subSlug: "chanachur-mixtures",
      brandSlug: "deshi-naturals",
      stock: 90,
      featured: false,
      tags: ["Peanuts", "China Badam", "Roasted"],
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-PNT-300G",
      weight: 0.3,
      description: "Freshly roasted Bangladeshi deshi peanuts seasoned with rock salt.",
    },
    {
      name: "Deluxe Energy Dry Fruit & Nut Mix 300g",
      slug: "deluxe-energy-dry-fruit-nut-mix-300g",
      price: 520,
      comparePrice: 620,
      categorySlug: "snacks",
      subSlug: "dry-fruit-mix",
      brandSlug: "pure-harvest",
      stock: 55,
      featured: true,
      tags: ["Dry Fruit", "Trail Mix", "Energy", "Nuts"],
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-MIX-300G",
      weight: 0.3,
      description: "Premium blend of almonds, cashews, raisins, pumpkin seeds, and dates.",
    },
    {
      name: "Traditional Sweet Handmade Khaja 400g",
      slug: "traditional-sweet-handmade-khaja-400g",
      price: 180,
      comparePrice: 220,
      categorySlug: "snacks",
      subSlug: "traditional-sweets",
      brandSlug: "deshi-naturals",
      stock: 40,
      featured: false,
      tags: ["Khaja", "Misti", "Deshi"],
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-KHJ-400G",
      weight: 0.4,
      description: "Flaky layered traditional Bengali sweet snack.",
    },
    {
      name: "Premium Handmade Gawa Ghee Toast Biscuit 350g",
      slug: "premium-handmade-gawa-ghee-toast-biscuit-350g",
      price: 190,
      comparePrice: 240,
      categorySlug: "snacks",
      subSlug: "traditional-sweets",
      brandSlug: "shomi",
      stock: 50,
      featured: false,
      tags: ["Toast", "Ghee Biscuit", "Tea Time"],
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-TST-350G",
      weight: 0.35,
      description: "Crispy oven baked toast biscuits made with 100% pure cow ghee.",
    },
    {
      name: "Crunchy Roasted Masala Makhana 100g",
      slug: "crunchy-roasted-masala-makhana-100g",
      price: 290,
      comparePrice: 350,
      categorySlug: "snacks",
      subSlug: "dry-fruit-mix",
      brandSlug: "nature-basket",
      stock: 8, // Low stock
      featured: false,
      tags: ["Makhana", "Fox Nuts", "Low Calorie"],
      imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-MKH-100G",
      weight: 0.1,
      description: "Spicy roasted lotus seed pops rich in plant calcium and fiber.",
    },
    {
      name: "Artisanal Handcrafted Nakshi Pitha Box (12 pcs)",
      slug: "artisanal-handcrafted-nakshi-pitha-box-12-pcs",
      price: 380,
      comparePrice: 450,
      categorySlug: "snacks",
      subSlug: "traditional-sweets",
      brandSlug: "deshi-naturals",
      stock: 30,
      featured: true,
      tags: ["Nakshi Pitha", "Heritage", "Festive"],
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-PTH-12PC",
      weight: 0.4,
      description: "Authentic festival delicacy hand-carved with traditional floral motifs and soaked in gur.",
    },
    {
      name: "Deshi Sweet Narkel Naru Jar (20 pcs)",
      slug: "deshi-sweet-narkel-naru-jar-20-pcs",
      price: 250,
      comparePrice: 300,
      categorySlug: "snacks",
      subSlug: "traditional-sweets",
      brandSlug: "deshi-naturals",
      stock: 45,
      featured: false,
      tags: ["Narkel Naru", "Coconut Laddu", "Traditional"],
      imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&auto=format&fit=crop&q=80",
      sku: "SNK-NAR-20PC",
      weight: 0.35,
      description: "Delicious traditional coconut balls sweetened with date palm jaggery.",
    },

    // 91-100: Cooking Essentials (10 items)
    {
      name: "Organic Sugarcane Unrefined Brown Sugar 1kg",
      slug: "organic-sugarcane-unrefined-brown-sugar-1kg",
      price: 180,
      comparePrice: 220,
      categorySlug: "cooking-essentials",
      subSlug: "sugar-jaggery",
      brandSlug: "nirapod-foods",
      stock: 100,
      featured: true,
      tags: ["Brown Sugar", "Lal Chini", "Unrefined", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-SGR-1KG",
      weight: 1.0,
      description: "Chemical-free unbleached brown sugar from natural sugarcane juice.",
    },
    {
      name: "Organic Date Palm Jaggery (Gur Patali) 500g",
      slug: "organic-date-palm-jaggery-gur-patali-500g",
      price: 320,
      comparePrice: 390,
      categorySlug: "cooking-essentials",
      subSlug: "sugar-jaggery",
      brandSlug: "nirapod-foods",
      stock: 60,
      featured: true,
      tags: ["Khejur Gur", "Patali Gur", "Winter Delicacy"],
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-GUR-500G",
      weight: 0.5,
      description: "Solid aromatic date palm jaggery patali made by traditional Gachhis.",
    },
    {
      name: "Traditional Liquid Date Palm Nolen Gur 750ml",
      slug: "traditional-liquid-date-palm-nolen-gur-750ml",
      price: 480,
      comparePrice: 580,
      categorySlug: "cooking-essentials",
      subSlug: "sugar-jaggery",
      brandSlug: "nirapod-foods",
      stock: 35,
      featured: true,
      tags: ["Nolen Gur", "Liquid Jaggery", "Pitha"],
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-NLN-750ML",
      weight: 0.75,
      description: "Exquisite liquid fresh Nolen Gur, ideal for winter payesh and pitha recipes.",
    },
    {
      name: "Stone-Ground Whole Wheat Atta 2kg",
      slug: "stone-ground-whole-wheat-atta-2kg",
      price: 140,
      comparePrice: 170,
      categorySlug: "cooking-essentials",
      subSlug: "flour-atta",
      brandSlug: "nirapod-foods",
      stock: 150,
      featured: true,
      tags: ["Atta", "Chakki Atta", "Whole Wheat", "Best Seller"],
      imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-ATT-2KG",
      weight: 2.0,
      description: "100% whole grain chakki atta with full dietary bran and fiber for soft rotis.",
    },
    {
      name: "Pure Natural Sugarcane Vinegar (Sirka) 500ml",
      slug: "pure-natural-sugarcane-vinegar-sirka-500ml",
      price: 160,
      comparePrice: 190,
      categorySlug: "cooking-essentials",
      subSlug: "vinegar-seasonings",
      brandSlug: "nirapod-foods",
      stock: 70,
      featured: false,
      tags: ["Sirka", "Sugarcane Vinegar", "Pickling"],
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-VNG-500ML",
      weight: 0.5,
      description: "Traditionally brewed sugarcane vinegar for pickling, marinades, and chutneys.",
    },
    {
      name: "Organic Seedless Tamarind (Tetul) Block 250g",
      slug: "organic-seedless-tamarind-tetul-block-250g",
      price: 90,
      comparePrice: 110,
      categorySlug: "cooking-essentials",
      subSlug: "vinegar-seasonings",
      brandSlug: "deshi-naturals",
      stock: 80,
      featured: false,
      tags: ["Tetul", "Tamarind", "Chutney"],
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-TTL-250G",
      weight: 0.25,
      description: "Clean seedless aged dark tamarind pulp for flavorful sour chutneys.",
    },
    {
      name: "Roasted Cumin & Black Salt Chotpoti Masala 150g",
      slug: "roasted-cumin-black-salt-chotpoti-masala-150g",
      price: 130,
      comparePrice: 160,
      categorySlug: "cooking-essentials",
      subSlug: "vinegar-seasonings",
      brandSlug: "deshi-naturals",
      stock: 60,
      featured: false,
      tags: ["Chotpoti Masala", "Street Food", "Tangy"],
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-CHT-150G",
      weight: 0.15,
      description: "Tangy spicy street-style seasoning for Fuchka, Chotpoti, and fruit salads.",
    },
    {
      name: "Premium Deshi Garlic Granules 150g",
      slug: "premium-deshi-garlic-granules-150g",
      price: 160,
      comparePrice: 190,
      categorySlug: "cooking-essentials",
      subSlug: "vinegar-seasonings",
      brandSlug: "nirapod-foods",
      stock: 45,
      featured: false,
      tags: ["Garlic", "Roshun", "Seasoning"],
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-GRL-150G",
      weight: 0.15,
      description: "Dehydrated pure deshi garlic granules for instant seasoning.",
    },
    {
      name: "Pure Ginger (Ada) Powder 150g",
      slug: "pure-ginger-ada-powder-150g",
      price: 150,
      comparePrice: 180,
      categorySlug: "cooking-essentials",
      subSlug: "vinegar-seasonings",
      brandSlug: "nirapod-foods",
      stock: 50,
      featured: false,
      tags: ["Ginger", "Ada", "Herbal"],
      imageUrl: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-GNG-150G",
      weight: 0.15,
      description: "Fine sun-dried ginger root powder for cooking and herbal tea.",
    },
    {
      name: "Himalayan Black Rock Salt (Bit Laban) 250g",
      slug: "himalayan-black-rock-salt-bit-laban-250g",
      price: 80,
      comparePrice: 100,
      categorySlug: "cooking-essentials",
      subSlug: "vinegar-seasonings",
      brandSlug: "nirapod-foods",
      stock: 120,
      featured: false,
      tags: ["Bit Laban", "Black Salt", "Digestive"],
      imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=800&auto=format&fit=crop&q=80",
      sku: "CKG-BIT-250G",
      weight: 0.25,
      description: "Traditional savory volcanic black salt powder for digestive drinks and snacks.",
    },
  ];

  console.log(`📦 [Seed] Processing ${productsData.length} products...`);

  let countUpserted = 0;

  for (const p of productsData) {
    const parentCatId = categoryMap.get(p.categorySlug);
    const subCatId = subcategoryMap.get(p.subSlug);
    const bId = brandMap.get(p.brandSlug);

    const categoryIds = [parentCatId, subCatId].filter(Boolean) as mongoose.Types.ObjectId[];

    const catDef = categoryDefs.find((c) => c.slug === p.categorySlug);
    const brandDef = brandDefs.find((b) => b.slug === p.brandSlug);

    await ProductModel.findOneAndUpdate(
      { storeId, slug: p.slug },
      {
        $set: {
          storeId,
          name: p.name,
          nameEn: p.name,
          nameBn: p.name,
          slug: p.slug,
          description: p.description,
          descriptionEn: p.description,
          descriptionBn: p.description,
          productType: "simple",
          price: p.price,
          comparePrice: p.comparePrice,
          category: catDef?.name || "General",
          categoryId: parentCatId || null,
          subcategoryId: subCatId || null,
          categoryIds,
          brand: brandDef?.name || "",
          brandId: bId || null,
          stock: p.stock,
          trackInventory: true,
          lowStockThreshold: 10,
          status: "active",
          sku: p.sku,
          imageUrl: p.imageUrl,
          thumbnailUrl: p.imageUrl,
          images: [p.imageUrl],
          galleryImageUrls: [p.imageUrl],
          featured: p.featured,
          tags: p.tags,
          weight: p.weight,
          weightUnit: "kg",
          seo: {
            title: `${p.name} | Buy Online at Best Price in Bangladesh`,
            description: p.description,
            keywords: p.tags,
          },
        },
      },
      { upsert: true, new: true }
    );
    countUpserted++;
  }

  console.log(`🎉 [Seed] Successfully seeded and synchronized ${countUpserted} products for Nayeem store!`);
  return { ok: true, count: countUpserted };
}

// If run directly from CLI
if (process.argv[1] && process.argv[1].endsWith("seed-nayeem-store.ts")) {
  seedNayeemStoreData()
    .then(() => {
      console.log("✅ [Seed] Done!");
      process.exit(0);
    })
    .catch((err) => {
      console.error("❌ [Seed] Error:", err);
      process.exit(1);
    });
}
