import { env } from "@/config/env";

export const config = {
  appName: env.APP_NAME,
  rootDomain: env.ROOT_DOMAIN,
  publicRootDomain: env.NEXT_PUBLIC_ROOT_DOMAIN,
  protocol: env.PROTOCOL,
  appUrl: env.APP_URL,
  apiUrl: env.API_URL,
  apiServerUrl: env.API_SERVER_URL,
  assetUrl: env.ASSET_URL,
  socketUrl: env.SOCKET_URL,
  defaultCurrency: env.DEFAULT_CURRENCY,
  defaultLocale: env.DEFAULT_LOCALE,
  enableSubdomain: env.ENABLE_SUBDOMAIN,
  enableAI: env.ENABLE_AI,
  enableAnalytics: env.ENABLE_ANALYTICS,
  enableBuilder: env.ENABLE_BUILDER,
  googleClientId: env.GOOGLE_CLIENT_ID,
  wildcardDomain: env.WILDCARD_DOMAIN,
  sessionCookieName: env.SESSION_COOKIE_NAME,
  appPort: env.APP_PORT,
  apiPort: env.API_PORT,
  isDev: env.isDev,
  isProd: env.isProd,
  smtpHost: env.SMTP_HOST,
  smtpPort: env.SMTP_PORT,
  smtpUser: env.SMTP_USER,
  smtpPass: env.SMTP_PASS,
  emailFrom: env.EMAIL_FROM,
} as const;
